const QUESTIONS = [
  { id:"sujebi-2026-sw-design-13", sourceQuestionNo:13, sourcePage:"1-74", questionType:"single_choice", questionText:"시스템의 구성요소로 볼 수 없는 것은?", choices:["Process","Feedback","Maintenance","Control"], sourceAnswer:3, aiDetectedAnswer:3, aiReasonedAnswer:3, sourceExplanation:"시스템의 기본 구성요소는 입력, 출력, 처리, 제어, 피드백으로 정리된다. Maintenance는 구성요소에 포함되지 않는다.", finalKey:"시스템 구성요소 = 입력·출력·처리·제어·피드백", sourceImageUrl:"https://drive.google.com/file/d/1qb0l0WaaKV1lq8o6sKoQfl-w2_ZvNjQ_/view" },
  { id:"sujebi-2026-sw-design-14", sourceQuestionNo:14, sourcePage:"1-74", questionType:"single_choice", questionText:"트랜잭션이 올바르게 처리되고 있는지 데이터를 감시하고 제어하는 미들웨어는?", choices:["RPC","ORB","TP Monitor","HUB"], sourceAnswer:3, aiDetectedAnswer:3, aiReasonedAnswer:3, sourceExplanation:"TP Monitor는 온라인 업무에서 트랜잭션을 처리하고 감시하는 트랜잭션 처리 미들웨어다.", finalKey:"트랜잭션 처리·감시 = TP Monitor", sourceImageUrl:"https://drive.google.com/file/d/1qb0l0WaaKV1lq8o6sKoQfl-w2_ZvNjQ_/view" },
  { id:"sujebi-2026-sw-design-15", sourceQuestionNo:15, sourcePage:"1-75", questionType:"single_choice", questionText:"미들웨어 솔루션의 유형에 포함되지 않는 것은?", choices:["WAS","Web Server","RPC","ORB"], sourceAnswer:2, aiDetectedAnswer:2, aiReasonedAnswer:2, sourceExplanation:"WAS, RPC, ORB는 미들웨어 솔루션 유형에 포함되지만 일반 Web Server 자체는 해당 유형으로 보지 않는다.", finalKey:"Web Server ≠ 미들웨어 솔루션 유형", sourceImageUrl:"https://drive.google.com/file/d/1H8D2mdVd08IQD2PU4E7x_z2j8ukn4EOs/view" },
  { id:"sujebi-2026-sw-design-16", sourceQuestionNo:16, sourcePage:"1-75", questionType:"single_choice", questionText:"클라이언트와 서버 간의 통신을 담당하는 시스템 소프트웨어를 무엇이라고 하는가?", choices:["웨어러블","하이웨어","미들웨어","응용 소프트웨어"], sourceAnswer:3, aiDetectedAnswer:3, aiReasonedAnswer:3, sourceExplanation:"클라이언트와 서버 사이에서 통신과 서비스 연결을 담당하는 시스템 소프트웨어를 미들웨어라고 한다.", finalKey:"클라이언트 ↔ 서버 통신 중계 = 미들웨어", sourceImageUrl:"https://drive.google.com/file/d/1H8D2mdVd08IQD2PU4E7x_z2j8ukn4EOs/view" },
  { id:"sujebi-2026-sw-design-17", sourceQuestionNo:17, sourcePage:"1-75", questionType:"single_choice", questionText:"분산 컴퓨팅 환경에서 서로 다른 기종 간 하드웨어·프로토콜·통신환경 등을 연결하여 응용 프로그램과 운영환경 간 원만한 통신이 이루어지도록 서비스를 제공하는 소프트웨어는?", choices:["미들웨어","하드웨어","오픈허브웨어","그레이웨어"], sourceAnswer:1, aiDetectedAnswer:1, aiReasonedAnswer:1, sourceExplanation:"이기종 환경 사이의 연결과 통신을 중개하여 분산 서비스를 제공하는 소프트웨어가 미들웨어다.", finalKey:"이기종 환경 연결·중개 = 미들웨어", sourceImageUrl:"https://drive.google.com/file/d/1H8D2mdVd08IQD2PU4E7x_z2j8ukn4EOs/view" },
  { id:"sujebi-2026-sw-design-18", sourceQuestionNo:18, sourcePage:"1-75", questionType:"single_choice", questionText:"응용 프로그램의 프로시저를 사용하여 원격 프로시저를 로컬 프로시저처럼 호출하는 방식의 미들웨어는?", choices:["WAS (Web Application Server)","MOM (Message Oriented Middleware)","RPC (Remote Procedure Call)","ORB (Object Request Broker)"], sourceAnswer:3, aiDetectedAnswer:3, aiReasonedAnswer:3, sourceExplanation:"원격의 프로시저를 로컬 함수처럼 호출하도록 하는 방식은 RPC다.", finalKey:"원격 프로시저를 로컬처럼 호출 = RPC", sourceImageUrl:"https://drive.google.com/file/d/1H8D2mdVd08IQD2PU4E7x_z2j8ukn4EOs/view" },
  { id:"sujebi-2026-sw-design-19", sourceQuestionNo:19, sourcePage:"1-76", questionType:"single_choice", questionText:"통신을 위한 프로그램을 생성하여 포트를 할당하고, 클라이언트의 통신 요청 시 클라이언트와 연결하는 내·외부 송수신 연계기술은?", choices:["DB 링크 기술","소켓 기술","스크립트 기술","프로토타입 기술"], sourceAnswer:2, aiDetectedAnswer:2, aiReasonedAnswer:2, sourceExplanation:"서버가 통신 소켓을 만들고 포트를 할당한 뒤 클라이언트 요청 시 연결하여 통신하는 방식은 소켓 기술이다.", finalKey:"포트 할당 + 클라이언트 연결 = Socket", sourceImageUrl:"https://drive.google.com/file/d/1I6fBunpRSGo75twJj6dz6Xg8RaniaHgE/view" },
  { id:"sujebi-2026-sw-design-20", sourceQuestionNo:20, sourcePage:"1-76", questionType:"single_choice", questionText:"분산 시스템에서의 미들웨어와 관련한 설명으로 틀린 것은?", choices:["분산 시스템에서 다양한 부분을 관리하고 통신하며 데이터를 교환하게 해주는 소프트웨어로 볼 수 있다.","위치 투명성(Location Transparency)을 제공한다.","분산 시스템의 여러 컴포넌트가 요구하는 재사용 가능한 서비스의 구현을 제공한다.","애플리케이션과 사용자 사이에서만 분산 서비스를 제공한다."], sourceAnswer:4, aiDetectedAnswer:4, aiReasonedAnswer:4, sourceExplanation:"미들웨어는 사용자와 애플리케이션 사이에만 한정되지 않고 애플리케이션·운영환경 등 다양한 계층과 환경에서 분산 서비스를 중개한다.", finalKey:"미들웨어는 '사용자-앱 사이에서만' 동작하지 않는다", sourceImageUrl:"https://drive.google.com/file/d/1I6fBunpRSGo75twJj6dz6Xg8RaniaHgE/view" },
  { id:"sujebi-2026-sw-design-21", sourceQuestionNo:21, sourcePage:"1-76", questionType:"single_choice", questionText:"미들웨어(Middleware)에 대한 설명으로 틀린 것은?", choices:["여러 운영체제에서 응용 프로그램들 사이에 위치한 소프트웨어이다.","미들웨어의 서비스 이용을 위해 사용자가 정보 교환 방법 등의 내부 동작을 쉽게 확인할 수 있어야 한다.","소프트웨어 컴포넌트를 연결하기 위한 준비된 인프라 구조를 제공한다.","여러 컴포넌트를 1대1, 1대다, 다대다 등 여러 형태로 연결할 수 있다."], sourceAnswer:2, aiDetectedAnswer:2, aiReasonedAnswer:2, sourceExplanation:"미들웨어는 내부 통신과 처리의 복잡성을 감추는 계층이므로 사용자가 내부 동작을 직접 확인해야 할 필요가 없다.", finalKey:"미들웨어 = 내부 복잡성 은닉", sourceImageUrl:"https://drive.google.com/file/d/1I6fBunpRSGo75twJj6dz6Xg8RaniaHgE/view" },
  { id:"sujebi-2026-sw-design-22", sourceQuestionNo:22, sourcePage:"1-76", questionType:"single_choice", questionText:"메시지 지향 미들웨어(MOM; Message-Oriented Middleware)에 대한 설명으로 틀린 것은?", choices:["느리고 안정적인 응답보다는 즉각적인 응답이 필요한 온라인 업무에 적합하다.","독립적인 애플리케이션을 하나의 통합된 시스템으로 묶기 위한 역할을 한다.","송신 측과 수신 측의 연결 시 메시지 큐를 활용하는 방법이 있다.","상이한 애플리케이션 간 통신을 비동기 방식으로 지원한다."], sourceAnswer:1, aiDetectedAnswer:1, aiReasonedAnswer:1, sourceExplanation:"MOM은 메시지 기반 비동기 통신에 적합하며 즉각적 응답이 필수인 업무보다는 느리더라도 안정적인 처리가 필요한 경우에 많이 사용한다.", finalKey:"MOM = 메시지 큐 + 비동기 + 안정적 처리", sourceImageUrl:"https://drive.google.com/file/d/1I6fBunpRSGo75twJj6dz6Xg8RaniaHgE/view" }
];

const STORAGE_KEY = "qtimer-v0.1-local";
const defaultState = { currentIndex:0, mode:"rapid", timerPolicy:"hard", timeLimitSec:20, autoDelayMs:500, attempts:[], overrides:{}, flags:{}, currentRoundIds:QUESTIONS.map(q=>q.id) };
let state = loadState();
let selectedAnswer = null;
let confidence = "sure";
let questionStart = 0;
let elapsedBeforePause = 0;
let timerRunning = false;
let timerHandle = null;
let submitted = false;
let lastAttemptId = null;

const els = Object.fromEntries([
  "progressText","weakCount","modeSelect","timerPolicy","timeLimit","autoDelay","restartBtn","questionTitle","sourceMeta","sourceImageLink","timer","timerState","pauseBtn","questionText","choices","sureBtn","ambiguousBtn","unknownBtn","submitBtn","nextBtn","undoBtn","preSubmitMessage","resultContent","correctnessBadge","confidenceBadge","timeBadge","userAnswerText","effectiveAnswerText","finalKey","sourceExplanation","sourceAnswer","aiDetectedAnswer","aiReasonedAnswer","userVerifiedAnswer","verificationState","verifiedAnswerSelect","verifyBtn","flagBtn","flagState","attemptedMetric","correctMetric","wrongMetric","ambiguousMetric","unknownMetric","overMetric"
].map(id => [id, document.querySelector(`#${id}`)]));

function loadState(){ try { const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)); return {...defaultState,...(saved||{})}; } catch { return structuredClone(defaultState); } }
function saveState(){ localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function currentQuestion(){ const id=state.currentRoundIds[state.currentIndex]; return QUESTIONS.find(q=>q.id===id)||QUESTIONS[0]; }
function effectiveAnswer(q){ return Number(state.overrides[q.id]?.answer ?? q.sourceAnswer); }
function answerLabel(value){ return value==null ? "미응답" : `${value}번`; }
function weakQuestionIds(){ const byQuestion=new Map(); for(const a of state.attempts) byQuestion.set(a.questionId,a); return QUESTIONS.filter(q=>{ const a=byQuestion.get(q.id); if(!a) return false; return !a.isCorrect||a.ambiguous||a.confidence==="unknown"||a.timedOut||!a.withinLimit; }).map(q=>q.id); }
function applyModeDefaults(){ if(state.mode==="rapid"){state.timerPolicy="hard";state.timeLimitSec=20;} else if(state.mode==="learn"){state.timerPolicy="soft";state.timeLimitSec=40;} else {state.timerPolicy="soft";state.timeLimitSec=45;const weak=weakQuestionIds();state.currentRoundIds=weak.length?weak:QUESTIONS.map(q=>q.id);state.currentIndex=0;} }
function renderSettings(){ els.modeSelect.value=state.mode; els.timerPolicy.value=state.timerPolicy; els.timeLimit.value=state.timeLimitSec; els.autoDelay.value=String(state.autoDelayMs); }
function escapeHtml(value){ return String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;"); }

function renderQuestion(){ stopTimer(); selectedAnswer=null; confidence="sure"; submitted=false; elapsedBeforePause=0; const q=currentQuestion();
  els.questionTitle.textContent=`문제 ${q.sourceQuestionNo}`; els.sourceMeta.textContent=`수제비 2026 · 소프트웨어 설계 · p.${q.sourcePage}`; els.sourceImageLink.href=q.sourceImageUrl; els.questionText.textContent=q.questionText; els.choices.innerHTML="";
  q.choices.forEach((choice,idx)=>{ const number=idx+1; const button=document.createElement("button"); button.type="button"; button.className="choice"; button.dataset.answer=String(number); button.innerHTML=`<span class="choice-number">${number}</span><span>${escapeHtml(choice)}</span>`; button.addEventListener("click",()=>selectAnswer(number)); els.choices.appendChild(button); });
  renderConfidence(); els.submitBtn.disabled=false; els.nextBtn.disabled=true; els.preSubmitMessage.hidden=false; els.resultContent.hidden=true; els.timer.textContent="00.0"; els.timerState.textContent="RUN"; renderVerification(q); updateProgress(); startTimer();
}

function selectAnswer(number){ if(submitted)return; selectedAnswer=number; [...els.choices.children].forEach(btn=>btn.classList.toggle("selected",Number(btn.dataset.answer)===number)); }
function setConfidence(next){ if(submitted)return; confidence=next; if(next==="unknown") selectedAnswer=null; renderConfidence(); if(next==="unknown") [...els.choices.children].forEach(btn=>btn.classList.remove("selected")); }
function renderConfidence(){ els.sureBtn.classList.toggle("active",confidence==="sure"); els.ambiguousBtn.classList.toggle("active",confidence==="ambiguous"); els.unknownBtn.classList.toggle("active",confidence==="unknown"); }
function startTimer(){ if(timerRunning||submitted)return; questionStart=performance.now(); timerRunning=true; els.timerState.textContent=elapsedBeforePause>0?"RESUME":"RUN"; timerHandle=requestAnimationFrame(tick); }
function stopTimer(){ if(timerHandle)cancelAnimationFrame(timerHandle); timerHandle=null; timerRunning=false; }
function pauseTimer(){ if(submitted)return; if(timerRunning){elapsedBeforePause=getElapsedMs();stopTimer();els.timerState.textContent="PAUSE";}else startTimer(); }
function getElapsedMs(){ return elapsedBeforePause+(timerRunning?performance.now()-questionStart:0); }
function tick(){ if(!timerRunning||submitted)return; const elapsed=getElapsedMs(); els.timer.textContent=(elapsed/1000).toFixed(1).padStart(4,"0"); const limitMs=state.timeLimitSec*1000; if(state.timerPolicy!=="none"&&elapsed>=limitMs){ els.timerState.textContent="OVER"; if(state.timerPolicy==="hard"){submitAttempt(true);return;} } timerHandle=requestAnimationFrame(tick); }

function submitAttempt(timedOut=false){ if(submitted)return; const q=currentQuestion(); const elapsedMs=getElapsedMs(); stopTimer(); submitted=true; const limitMs=state.timerPolicy==="none"?null:state.timeLimitSec*1000; const withinLimit=limitMs==null?true:elapsedMs<=limitMs; const answer=confidence==="unknown"?null:selectedAnswer; const correct=effectiveAnswer(q); const isCorrect=answer!=null&&answer===correct; const attempt={ id:crypto.randomUUID(), questionId:q.id, sourceQuestionNo:q.sourceQuestionNo, userAnswer:answer, effectiveAnswer:correct, isCorrect, confidence, ambiguous:confidence==="ambiguous", elapsedMs:Math.round(elapsedMs), timeLimitMs:limitMs, withinLimit, timedOut:Boolean(timedOut), createdAt:new Date().toISOString() };
  state.attempts.push(attempt); lastAttemptId=attempt.id; saveState(); renderResult(attempt,q); updateProgress(); els.submitBtn.disabled=true; els.nextBtn.disabled=false; if(timedOut&&state.timerPolicy==="hard"){els.timerState.textContent="TIME OUT";window.setTimeout(nextQuestion,state.autoDelayMs);} }

function renderResult(attempt,q){ els.preSubmitMessage.hidden=true; els.resultContent.hidden=false; els.correctnessBadge.textContent=attempt.userAnswer==null?"? 미응답":attempt.isCorrect?"✅ 정답":"❌ 오답"; els.confidenceBadge.textContent=attempt.confidence==="sure"?"확실":attempt.confidence==="ambiguous"?"△ 애매":"? 모름"; els.timeBadge.textContent=attempt.withinLimit?`⏱ IN ${(attempt.elapsedMs/1000).toFixed(1)}s`:`⏱ OVER ${(attempt.elapsedMs/1000).toFixed(1)}s`; els.userAnswerText.textContent=answerLabel(attempt.userAnswer); els.effectiveAnswerText.textContent=answerLabel(attempt.effectiveAnswer); els.finalKey.textContent=q.finalKey; els.sourceExplanation.textContent=q.sourceExplanation;
  [...els.choices.children].forEach(btn=>{ const value=Number(btn.dataset.answer); btn.classList.remove("selected"); if(value===attempt.effectiveAnswer)btn.classList.add("correct"); if(attempt.userAnswer!=null&&value===attempt.userAnswer&&!attempt.isCorrect)btn.classList.add("wrong"); btn.disabled=true; }); renderVerification(q); }

function nextQuestion(){ if(!submitted)return; state.currentIndex+=1; if(state.currentIndex>=state.currentRoundIds.length)state.currentIndex=0; saveState(); renderQuestion(); }
function restartRound(){ state.currentRoundIds=state.mode==="weak"?(weakQuestionIds().length?weakQuestionIds():QUESTIONS.map(q=>q.id)):QUESTIONS.map(q=>q.id); state.currentIndex=0; saveState(); renderQuestion(); }
function undoLastAttempt(){ if(!state.attempts.length)return; const removed=state.attempts.pop(); if(removed?.id===lastAttemptId)lastAttemptId=null; saveState(); updateProgress(); }

function renderVerification(q){ const override=state.overrides[q.id]; els.sourceAnswer.textContent=answerLabel(q.sourceAnswer); els.aiDetectedAnswer.textContent=answerLabel(q.aiDetectedAnswer); els.aiReasonedAnswer.textContent=answerLabel(q.aiReasonedAnswer); els.userVerifiedAnswer.textContent=override?answerLabel(override.answer):"미검증"; const allMatch=q.sourceAnswer===q.aiDetectedAnswer&&q.sourceAnswer===q.aiReasonedAnswer; els.verificationState.textContent=override?`🔵 사용자 검증 · ${new Date(override.verifiedAt).toLocaleString("ko-KR")}`:allMatch?"🟢 자동일치 (사용자 검증 전)":"🟡 검토필요"; els.verifiedAnswerSelect.innerHTML=q.choices.map((_,idx)=>`<option value="${idx+1}">${idx+1}번</option>`).join(""); els.verifiedAnswerSelect.value=String(effectiveAnswer(q)); const flag=state.flags[q.id]; els.flagState.textContent=flag?`⚑ 검토 표시됨 · ${new Date(flag.createdAt).toLocaleString("ko-KR")}`:""; }
function verifyCurrentAnswer(){ const q=currentQuestion(); const answer=Number(els.verifiedAnswerSelect.value); const previous=effectiveAnswer(q); state.overrides[q.id]={answer,previousAnswer:previous,verifiedAt:new Date().toISOString()}; if(previous!==answer)regradeQuestion(q.id,answer); saveState(); renderVerification(q); updateProgress(); }
function regradeQuestion(questionId,answer){ state.attempts=state.attempts.map(a=>a.questionId!==questionId?a:{...a,effectiveAnswer:answer,isCorrect:a.userAnswer!=null&&a.userAnswer===answer,regradedAt:new Date().toISOString()}); }
function flagCurrentQuestion(){ const q=currentQuestion(); state.flags[q.id]={createdAt:new Date().toISOString(),reason:"manual_review"}; saveState(); renderVerification(q); }
function updateProgress(){ const weak=weakQuestionIds(); els.progressText.textContent=`${state.currentIndex+1} / ${state.currentRoundIds.length}`; els.weakCount.textContent=`취약 ${weak.length}`; const attempts=state.attempts; els.attemptedMetric.textContent=attempts.length; els.correctMetric.textContent=attempts.filter(a=>a.isCorrect).length; els.wrongMetric.textContent=attempts.filter(a=>a.userAnswer!=null&&!a.isCorrect).length; els.ambiguousMetric.textContent=attempts.filter(a=>a.ambiguous).length; els.unknownMetric.textContent=attempts.filter(a=>a.confidence==="unknown").length; els.overMetric.textContent=attempts.filter(a=>!a.withinLimit||a.timedOut).length; }

els.modeSelect.addEventListener("change",()=>{state.mode=els.modeSelect.value;applyModeDefaults();saveState();renderSettings();restartRound();});
els.timerPolicy.addEventListener("change",()=>{state.timerPolicy=els.timerPolicy.value;saveState();});
els.timeLimit.addEventListener("change",()=>{state.timeLimitSec=Math.max(5,Number(els.timeLimit.value)||20);saveState();});
els.autoDelay.addEventListener("change",()=>{state.autoDelayMs=Number(els.autoDelay.value);saveState();});
els.restartBtn.addEventListener("click",restartRound); els.pauseBtn.addEventListener("click",pauseTimer); els.sureBtn.addEventListener("click",()=>setConfidence("sure")); els.ambiguousBtn.addEventListener("click",()=>setConfidence("ambiguous")); els.unknownBtn.addEventListener("click",()=>setConfidence("unknown")); els.submitBtn.addEventListener("click",()=>submitAttempt(false)); els.nextBtn.addEventListener("click",nextQuestion); els.undoBtn.addEventListener("click",undoLastAttempt); els.verifyBtn.addEventListener("click",verifyCurrentAnswer); els.flagBtn.addEventListener("click",flagCurrentQuestion);

document.addEventListener("keydown",event=>{ const tag=event.target?.tagName?.toLowerCase(); if(["input","select","textarea"].includes(tag))return; if(event.ctrlKey&&event.key.toLowerCase()==="z"){event.preventDefault();undoLastAttempt();return;} if(/^[1-4]$/.test(event.key))selectAnswer(Number(event.key)); else if(event.key.toLowerCase()==="a")setConfidence("ambiguous"); else if(event.key.toLowerCase()==="m")setConfidence("unknown"); else if(event.key.toLowerCase()==="p")pauseTimer(); else if(event.key===" "){event.preventDefault();pauseTimer();} else if(event.key==="Enter"){event.preventDefault();if(submitted)nextQuestion();else submitAttempt(false);} });

renderSettings();
renderQuestion();
