const CH03_QUESTIONS_01_22 = [
  {id:"sujebi-2026-sw-design-ch03-01",sourceQuestionNo:1,sourcePage:"1-39",questionType:"single_choice",questionText:"HIPO(Hierarchy Input Process Output)에 대한 설명으로 거리가 먼 것은?",choices:["상향식 소프트웨어 개발을 위한 문서화 도구이다.","HIPO 차트 종류에는 가시적 도표, 총체적 도표, 세부적 도표가 있다.","기능과 자료의 의존 관계를 동시에 표현할 수 있다.","보기 쉽고 이해하기 쉽다."],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"HIPO는 하향식 소프트웨어 개발을 위한 문서화 도구다. 기능과 자료의 의존관계를 표현하며 가시적·총체적·세부적 도표를 사용한다.",finalKey:"HIPO = 하향식 문서화 도구",sourceImageUrl:"https://drive.google.com/file/d/1ZcbL_qlBlDiLhKMTSYQxBvV02ahns4SH/view"},
  {id:"sujebi-2026-sw-design-ch03-02",sourceQuestionNo:2,sourcePage:"1-39",questionType:"single_choice",questionText:"공통 모듈에 대한 명세 기법 중 해당 기능에 대해 일관되게 이해되고 한 가지로 해석될 수 있도록 작성하는 원칙은?",choices:["상호 작용성","명확성","독립성","내용성"],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"명확성은 공통모듈 기능을 누구나 일관되게 이해하고 한 가지 의미로 해석할 수 있도록 명세하는 원칙이다.",finalKey:"한 가지로 해석되도록 명세 = 명확성",sourceImageUrl:"https://drive.google.com/file/d/1ZcbL_qlBlDiLhKMTSYQxBvV02ahns4SH/view"},
  {id:"sujebi-2026-sw-design-ch03-03",sourceQuestionNo:3,sourcePage:"1-39",questionType:"single_choice",questionText:"코드 설계에서 일정한 일련번호를 부여하는 방식의 코드는?",choices:["연상 코드","블록 코드","순차 코드","표의 숫자 코드"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"순차 코드는 일정한 기준에 따라 순서대로 일련번호를 부여하는 코드다.",finalKey:"일련번호 부여 = 순차 코드",sourceImageUrl:"https://drive.google.com/file/d/1ZcbL_qlBlDiLhKMTSYQxBvV02ahns4SH/view"},
  {id:"sujebi-2026-sw-design-ch03-04",sourceQuestionNo:4,sourcePage:"1-40",questionType:"single_choice",questionText:"다음 프로그램 구조에서 모듈 F의 Fan-in과 Fan-out 수는? (A→B,C,D / B→E,F / C→F / D→F / F→G,H)",choices:["Fan-In: 2, Fan-Out: 3","Fan-In: 3, Fan-Out: 2","Fan-In: 1, Fan-Out: 2","Fan-In: 2, Fan-Out: 1"],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"F로 들어오는 모듈은 B·C·D로 3개이고 F에서 나가는 모듈은 G·H로 2개다.",finalKey:"F: Fan-In 3 / Fan-Out 2",sourceImageUrl:"https://drive.google.com/file/d/1fDZdZrI30Qk1F8R1-ZwCtNeEFFotLzBv/view"},
  {id:"sujebi-2026-sw-design-ch03-05",sourceQuestionNo:5,sourcePage:"1-40",questionType:"single_choice",questionText:"코드의 기본 기능으로 거리가 먼 것은?",choices:["복잡성","표준화","분류","식별"],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"코드의 기본 기능에는 표준화, 분류, 식별, 배열, 간소화, 연상, 암호화, 오류 검출 등이 있다. 복잡성은 기능이 아니다.",finalKey:"코드 기능 ≠ 복잡성",sourceImageUrl:"https://drive.google.com/file/d/1fDZdZrI30Qk1F8R1-ZwCtNeEFFotLzBv/view"},
  {id:"sujebi-2026-sw-design-ch03-06",sourceQuestionNo:6,sourcePage:"1-40",questionType:"single_choice",questionText:"바람직한 소프트웨어 설계 지침이 아닌 것은?",choices:["적당한 모듈의 크기를 유지한다.","모듈 간의 접속 관계를 분석하여 복잡도와 중복을 줄인다.","모듈 간의 결합도는 강할수록 바람직하다.","모듈 간의 효과적인 제어를 위해 설계에서 계층적 자료 조직이 제시되어야 한다."],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"효과적인 모듈 설계에서는 결합도를 낮춰 모듈 독립성을 높여야 한다.",finalKey:"좋은 설계 = 낮은 결합도",sourceImageUrl:"https://drive.google.com/file/d/1fDZdZrI30Qk1F8R1-ZwCtNeEFFotLzBv/view"},
  {id:"sujebi-2026-sw-design-ch03-07",sourceQuestionNo:7,sourcePage:"1-40",questionType:"single_choice",questionText:"소프트웨어 설계 시 고려사항으로 거리가 먼 것은?",choices:["전체적이고 포괄적인 개념을 설계한 후 차례로 세분화하고 구체화시켜 나간다.","요구사항을 모두 구현해야 하고 유지보수가 용이해야 한다.","모듈은 독립적인 기능을 갖도록 설계해야 한다.","모듈 간의 상관성은 높이고 변경이 쉬워야 한다."],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"모듈의 독립성을 확보하려면 모듈 간 상관성, 즉 결합도를 낮춰야 한다.",finalKey:"모듈 간 상관성·결합도는 낮게",sourceImageUrl:"https://drive.google.com/file/d/1fDZdZrI30Qk1F8R1-ZwCtNeEFFotLzBv/view"},
  {id:"sujebi-2026-sw-design-ch03-08",sourceQuestionNo:8,sourcePage:"1-41",questionType:"single_choice",questionText:"컴포넌트 설계 시 선행조건(Precondition), 결과조건(Postcondition), 불변조건(Invariant)을 명세하여 따르는 설계 방식은?",choices:["협약","프로토콜","패턴","관계"],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"협약에 의한 설계(Design by Contract)는 컴포넌트의 선행조건, 결과조건, 불변조건을 명시하는 설계 방법이다.",finalKey:"Pre/Post/Invariant = Design by Contract(협약)",sourceImageUrl:"https://drive.google.com/file/d/15j0PK_AVdKBdsHERJELFxMEsaTntBANW/view"},
  {id:"sujebi-2026-sw-design-ch03-09",sourceQuestionNo:9,sourcePage:"1-41",questionType:"single_choice",questionText:"코드화 대상 항목의 중량, 면적, 용량 등의 물리적 수치를 이용하여 만든 코드는?",choices:["순차 코드","10진 코드","표의 숫자 코드","블록 코드"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"표의 숫자 코드는 길이, 넓이, 용량, 중량 등 대상 자료의 물리적 수치를 이용하는 코드다.",finalKey:"물리적 수치 이용 = 표의 숫자 코드",sourceImageUrl:"https://drive.google.com/file/d/15j0PK_AVdKBdsHERJELFxMEsaTntBANW/view"},
  {id:"sujebi-2026-sw-design-ch03-10",sourceQuestionNo:10,sourcePage:"1-41",questionType:"single_choice",questionText:"파이프 필터 형태의 소프트웨어 아키텍처에 대한 설명으로 옳은 것은?",choices:["노드와 간선으로 구성된다.","서브 시스템이 입력 데이터를 받아 처리하고, 결과를 다음 서브 시스템으로 넘겨주는 과정을 반복한다.","계층 모델이라고도 한다.","3개의 서브 시스템(모델, 뷰, 제어)으로 구성되어 있다."],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"Pipe-Filter 패턴은 필터가 입력 데이터를 처리하고 결과를 파이프를 통해 다음 필터로 전달하는 과정을 반복한다.",finalKey:"입력 처리 → 다음 서브시스템 전달 반복 = Pipe-Filter",sourceImageUrl:"https://drive.google.com/file/d/15j0PK_AVdKBdsHERJELFxMEsaTntBANW/view"},
  {id:"sujebi-2026-sw-design-ch03-11",sourceQuestionNo:11,sourcePage:"1-41",questionType:"single_choice",questionText:"소프트웨어의 상위 설계에 속하지 않는 것은?",choices:["아키텍처 설계","모듈 설계","인터페이스 정의","사용자 인터페이스 설계"],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"아키텍처 설계, 인터페이스 설계, 사용자 인터페이스 설계 등은 상위 설계에 속하고 모듈 설계는 하위 설계에 속한다.",finalKey:"모듈 설계 = 하위 설계",sourceImageUrl:"https://drive.google.com/file/d/15j0PK_AVdKBdsHERJELFxMEsaTntBANW/view"},
  {id:"sujebi-2026-sw-design-ch03-12",sourceQuestionNo:12,sourcePage:"1-42",questionType:"single_choice",questionText:"코드의 기입 과정에서 원래 '12536'으로 기입되어야 하는데 '12936'으로 표기되었을 경우 어떤 코드 오류에 해당하는가?",choices:["Addition Error","Omission Error","Sequence Error","Transcription Error"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"한 자리를 잘못 표기한 오류는 사본 오류(Transcription Error)다.",finalKey:"한 자리 잘못 표기 = Transcription Error",sourceImageUrl:"https://drive.google.com/file/d/1lIbdHI5PxFoE97qFhBBCFjzs15igOY8W/view"},
  {id:"sujebi-2026-sw-design-ch03-13",sourceQuestionNo:13,sourcePage:"1-42",questionType:"single_choice",questionText:"바람직한 소프트웨어 설계 지침이 아닌 것은?",choices:["모듈의 기능을 예측할 수 있도록 정의한다.","이식성을 고려한다.","적당한 모듈의 크기를 유지한다.","가능한 모듈을 독립적으로 생성하고 결합도를 최대화한다."],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"모듈 독립성과 재사용성을 높이기 위해 결합도는 최대가 아니라 최소가 되어야 한다.",finalKey:"좋은 모듈 설계 = 결합도 최소화",sourceImageUrl:"https://drive.google.com/file/d/1lIbdHI5PxFoE97qFhBBCFjzs15igOY8W/view"},
  {id:"sujebi-2026-sw-design-ch03-14",sourceQuestionNo:14,sourcePage:"1-42",questionType:"single_choice",questionText:"소프트웨어 아키텍처 설계에서 시스템 품질 속성이 아닌 것은?",choices:["가용성(Availability)","독립성(Isolation)","변경 용이성(Modifiability)","사용성(Usability)"],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"대표적인 시스템 품질 속성에는 가용성, 변경 용이성, 성능, 보안성, 사용 편의성, 시험 용이성 등이 있다. 독립성은 해당 목록의 품질 속성이 아니다.",finalKey:"아키텍처 품질속성 ≠ Isolation",sourceImageUrl:"https://drive.google.com/file/d/1lIbdHI5PxFoE97qFhBBCFjzs15igOY8W/view"},
  {id:"sujebi-2026-sw-design-ch03-15",sourceQuestionNo:15,sourcePage:"1-42",questionType:"single_choice",questionText:"서브 시스템이 입력 데이터를 받아 처리하고 결과를 다른 시스템에 보내는 작업이 반복되는 아키텍처 스타일은?",choices:["클라이언트 서버 구조","계층 구조","MVC 구조","파이프 필터 구조"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"Pipe-Filter 패턴은 각 서브시스템이 입력을 처리하고 결과를 다음 서브시스템으로 전달하는 과정을 반복한다.",finalKey:"입력→처리→다음 시스템 전달 반복 = Pipe-Filter",sourceImageUrl:"https://drive.google.com/file/d/1lIbdHI5PxFoE97qFhBBCFjzs15igOY8W/view"},
  {id:"sujebi-2026-sw-design-ch03-16",sourceQuestionNo:16,sourcePage:"1-43",questionType:"single_choice",questionText:"분산 시스템을 위한 마스터-슬레이브(Master-Slave) 아키텍처에 대한 설명으로 틀린 것은?",choices:["일반적으로 실시간 시스템에서 사용된다.","마스터 프로세스는 일반적으로 연산, 통신, 조정을 책임진다.","슬레이브 프로세스는 데이터 수집 기능을 수행할 수 없다.","마스터 프로세스는 슬레이브 프로세스들을 제어할 수 있다."],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"슬레이브 프로세스도 데이터 수집 등의 기능을 수행할 수 있다. 마스터는 연산·통신·조정과 슬레이브 제어를 담당한다.",finalKey:"Master-Slave: Slave도 데이터 수집 가능",sourceImageUrl:"https://drive.google.com/file/d/1D729ICGsABkSOktKYrw2lCak9dcaVqXN/view"},
  {id:"sujebi-2026-sw-design-ch03-17",sourceQuestionNo:17,sourcePage:"1-43",questionType:"single_choice",questionText:"소프트웨어 아키텍처와 관련한 설명으로 틀린 것은?",choices:["파이프 필터 아키텍처에서 데이터는 파이프를 통해 양방향으로 흐르며, 필터 이동 시 오버헤드가 발생하지 않는다.","외부에서 인식할 수 있는 특성이 담긴 소프트웨어의 골격이 되는 기본 구조로 볼 수 있다.","데이터 중심 아키텍처는 공유 데이터 저장소를 통해 접근자 간 통신이 이루어지므로 각 접근자의 수정과 확장이 용이하다.","이해 관계자들의 품질 요구사항을 반영하여 품질 속성을 결정한다."],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"Pipe-Filter는 일반적으로 데이터 스트림이 한 방향으로 흐르며 필터 간 데이터 변환에 따른 오버헤드가 발생할 수 있다.",finalKey:"Pipe-Filter = 단방향 흐름, 변환 오버헤드 가능",sourceImageUrl:"https://drive.google.com/file/d/1D729ICGsABkSOktKYrw2lCak9dcaVqXN/view"},
  {id:"sujebi-2026-sw-design-ch03-18",sourceQuestionNo:18,sourcePage:"1-43",questionType:"single_choice",questionText:"소프트웨어 설계 시 제일 상위에 있는 main user function에서 시작하여 기능을 하위 기능들로 분할해 가면서 설계하는 방식은?",choices:["객체 지향 설계","데이터 흐름 설계","상향식 설계","하향식 설계"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"최상위 기능에서 시작해 하위 기능으로 점차 분해해 나가는 방식은 하향식 설계다.",finalKey:"상위 main function → 하위 기능 분해 = 하향식",sourceImageUrl:"https://drive.google.com/file/d/1D729ICGsABkSOktKYrw2lCak9dcaVqXN/view"},
  {id:"sujebi-2026-sw-design-ch03-19",sourceQuestionNo:19,sourcePage:"1-43",questionType:"single_choice",questionText:"소프트웨어 개발에서 모듈(Module)이 되기 위한 주요 특징에 해당하지 않는 것은?",choices:["다른 것들과 구별될 수 있는 독립적인 기능을 가진 단위(Unit)이다.","독립적인 컴파일이 가능하다.","유일한 이름을 가져야 한다.","다른 모듈에서의 접근이 불가능해야 한다."],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"모듈은 독립적으로 컴파일 가능하고 재사용할 수 있으며 다른 모듈에서 접근 가능해야 한다.",finalKey:"모듈 = 독립적이지만 다른 모듈에서 접근 가능",sourceImageUrl:"https://drive.google.com/file/d/1D729ICGsABkSOktKYrw2lCak9dcaVqXN/view"},
  {id:"sujebi-2026-sw-design-ch03-20",sourceQuestionNo:20,sourcePage:"1-44",questionType:"single_choice",questionText:"좋은 소프트웨어 설계를 위한 모듈 간 결합도(Coupling)와 모듈 내 요소 간 응집도(Cohesion)에 대한 설명으로 옳은 것은?",choices:["응집도는 낮게 결합도는 높게 설계한다.","응집도는 높게 결합도는 낮게 설계한다.","양쪽 모두 낮게 설계한다.","양쪽 모두 높게 설계한다."],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"좋은 모듈 설계는 모듈 내부 응집도를 높이고 모듈 간 결합도를 낮춰 독립성과 재사용성을 높인다.",finalKey:"좋은 모듈 = 응집도↑ 결합도↓",sourceImageUrl:"https://drive.google.com/file/d/1wfca9IbTNK5OBR0pBYG_i1G09fPW-10Z/view"},
  {id:"sujebi-2026-sw-design-ch03-21",sourceQuestionNo:21,sourcePage:"1-44",questionType:"single_choice",questionText:"설계 기법 중 하향식 설계 방법과 상향식 설계 방법에 대한 비교 설명으로 가장 옳지 않은 것은?",choices:["하향식 설계에서는 통합 검사 시 인터페이스가 이미 정의되어 있어 통합이 간단하다.","하향식 설계에서 레벨이 낮은 데이터 구조의 세부 사항은 설계 초기 단계에서 필요하다.","상향식 설계는 최하위 수준에서 각각의 모듈들을 설계하고 이러한 모듈이 완성되면 이들을 결합하여 검사한다.","상향식 설계에서는 인터페이스가 이미 성립되어 있지 않더라도 기능 추가가 쉽다."],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"상향식 설계는 하위 모듈을 먼저 만들고 결합하는 방식이며, 기능을 쉽게 추가하려면 모듈 간 인터페이스가 성립되어 있어야 한다.",finalKey:"상향식 기능 추가 용이 조건 = 인터페이스 성립",sourceImageUrl:"https://drive.google.com/file/d/1wfca9IbTNK5OBR0pBYG_i1G09fPW-10Z/view"},
  {id:"sujebi-2026-sw-design-ch03-22",sourceQuestionNo:22,sourcePage:"1-44",questionType:"single_choice",questionText:"소프트웨어 아키텍처 모델 중 MVC(Model-View-Controller)와 관련한 설명으로 틀린 것은?",choices:["MVC 모델은 사용자 인터페이스를 담당하는 계층의 응집도를 높일 수 있고, 여러 개의 다른 UI를 만들어 그 사이에 결합도를 낮출 수 있다.","모델(Model)은 뷰(View)와 제어(Controller) 사이에서 전달자 역할을 하며, 뷰마다 모델 서브 시스템이 각각 하나씩 연결된다.","뷰(View)는 모델(Model)에 있는 데이터를 사용자 인터페이스에 보이는 역할을 담당한다.","제어(Controller)는 모델(Model)에 명령을 보냄으로써 모델의 상태를 변경할 수 있다."],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"MVC에서 모델은 데이터와 핵심 기능을 담당하고, 컨트롤러가 사용자 요청을 처리하면서 모델과 뷰 사이의 전달자 역할을 수행한다.",finalKey:"MVC 전달자 = Controller, Model 아님",sourceImageUrl:"https://drive.google.com/file/d/1wfca9IbTNK5OBR0pBYG_i1G09fPW-10Z/view"}
];

const currentIdBeforeCh03_01_22 = state.currentRoundIds?.[state.currentIndex];
const knownCh03_01_22 = new Set(QUESTIONS.map(q => q.id));
const addCh03_01_22 = CH03_QUESTIONS_01_22.filter(q => !knownCh03_01_22.has(q.id));
if (addCh03_01_22.length) QUESTIONS.push(...addCh03_01_22);
const orderedCh03_01 = QUESTIONS.filter(q => q.id.startsWith("sujebi-2026-sw-design-ch03-")).sort((a,b) => a.sourceQuestionNo - b.sourceQuestionNo);
const orderedNonCh03_01 = QUESTIONS.filter(q => !q.id.startsWith("sujebi-2026-sw-design-ch03-"));
QUESTIONS.splice(0, QUESTIONS.length, ...orderedCh03_01, ...orderedNonCh03_01);
if (state.mode !== "weak") {
  state.currentRoundIds = QUESTIONS.map(q => q.id);
  const preserved = state.currentRoundIds.indexOf(currentIdBeforeCh03_01_22);
  state.currentIndex = preserved >= 0 ? preserved : Math.min(state.currentIndex || 0, state.currentRoundIds.length - 1);
  saveState();
}
if (typeof renderDashboardV01 === "function") renderDashboardV01();