const CH02_QUESTIONS_01_15 = [
  {id:"sujebi-2026-sw-design-ch02-01",sourceQuestionNo:1,sourcePage:"1-35",questionType:"single_choice",questionText:"UI 설계 원칙에서 누구나 쉽게 이해하고 사용할 수 있어야 한다는 것은?",choices:["유효성","직관성","무결성","유연성"],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"직관성은 누구나 쉽게 이해하고 쉽게 사용할 수 있도록 만드는 UI 설계 원칙이다.",finalKey:"누구나 쉽게 이해·사용 = 직관성",sourceImageUrl:"https://drive.google.com/file/d/1nl1d8DsgcwUur31TAbJIcFiyDV_EaQCe/view"},
  {id:"sujebi-2026-sw-design-ch02-02",sourceQuestionNo:2,sourcePage:"1-35",questionType:"single_choice",questionText:"UI 설계 원칙 중 누구나 쉽게 이해하고 사용할 수 있어야 한다는 원칙은?",choices:["희소성","유연성","직관성","멀티 응용성"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"직관성은 누구나 쉽게 이해하고 쉽게 사용할 수 있도록 하는 원칙이다.",finalKey:"쉽게 이해·사용 = 직관성",sourceImageUrl:"https://drive.google.com/file/d/1nl1d8DsgcwUur31TAbJIcFiyDV_EaQCe/view"},
  {id:"sujebi-2026-sw-design-ch02-03",sourceQuestionNo:3,sourcePage:"1-35",questionType:"single_choice",questionText:"소프트웨어의 사용자 인터페이스 개발 시스템(User Interface Development System)이 가져야 할 기능이 아닌 것은?",choices:["사용자 입력의 검증","에러 처리와 에러 메시지 처리","도움말 프롬프트(Prompt) 제공","소스 코드 분석 및 오류 복구"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"UI 개발 시스템은 사용자 입력 검증, 오류 처리와 메시지, 도움말·프롬프트 등을 제공하지만 소스 코드 분석 및 오류 복구는 핵심 UI 개발 기능이 아니다.",finalKey:"UI 개발 시스템 기능 ≠ 소스 코드 분석·오류 복구",sourceImageUrl:"https://drive.google.com/file/d/1nl1d8DsgcwUur31TAbJIcFiyDV_EaQCe/view"},
  {id:"sujebi-2026-sw-design-ch02-04",sourceQuestionNo:4,sourcePage:"1-35",questionType:"single_choice",questionText:"대표적으로 DOS 및 Unix 등의 운영체제에서 조작을 위해 정해진 명령 문자열을 입력하여 시스템을 조작하는 사용자 인터페이스는?",choices:["GUI(Graphical User Interface)","CLI(Command Line Interface)","CUI(Cell User Interface)","MUI(Mobile User Interface)"],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"CLI는 명령어를 텍스트로 입력하여 시스템을 조작하는 사용자 인터페이스다.",finalKey:"명령 문자열 입력 = CLI",sourceImageUrl:"https://drive.google.com/file/d/1nl1d8DsgcwUur31TAbJIcFiyDV_EaQCe/view"},
  {id:"sujebi-2026-sw-design-ch02-05",sourceQuestionNo:5,sourcePage:"1-36",questionType:"single_choice",questionText:"사용자 인터페이스(User Interface)에 대한 설명으로 틀린 것은?",choices:["사용자와 시스템이 정보를 주고받는 상호작용이 잘 이루어지도록 하는 장치나 소프트웨어를 의미한다.","편리한 유지보수를 위해 개발자 중심으로 설계되어야 한다.","배우기가 용이하고 쉽게 사용할 수 있도록 만들어져야 한다.","사용자 요구사항이 UI에 반영될 수 있도록 구성해야 한다."],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"UI는 개발자 중심이 아니라 사용자 중심으로 설계되어야 한다.",finalKey:"UI 설계 = 사용자 중심",sourceImageUrl:"https://drive.google.com/file/d/1ZSnaLDBgk0t0LmZZmELDm7GSAO68A3BA/view"},
  {id:"sujebi-2026-sw-design-ch02-06",sourceQuestionNo:6,sourcePage:"1-36",questionType:"single_choice",questionText:"사용자 인터페이스(UI)의 특징으로 틀린 것은?",choices:["구현하고자 하는 결과의 오류를 최소화한다.","사용자의 편의성을 높임으로써 작업시간을 증가시킨다.","막연한 작업 기능에 대해 구체적인 방법을 제시하여 준다.","사용자 중심의 상호 작용이 되도록 한다."],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"UI는 사용자 편의성을 높여 작업시간을 감소시키는 방향이어야 한다.",finalKey:"사용자 편의성↑ → 작업시간↓",sourceImageUrl:"https://drive.google.com/file/d/1ZSnaLDBgk0t0LmZZmELDm7GSAO68A3BA/view"},
  {id:"sujebi-2026-sw-design-ch02-07",sourceQuestionNo:7,sourcePage:"1-36",questionType:"single_choice",questionText:"여러 개의 선택 항목 중 하나의 선택만 가능한 경우 사용하는 사용자 인터페이스(UI) 요소는?",choices:["토글 버튼","텍스트 박스","라디오 버튼","체크박스"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"라디오 버튼은 여러 선택지 중 하나만 선택할 때 사용하는 UI 요소다.",finalKey:"여러 항목 중 1개만 선택 = 라디오 버튼",sourceImageUrl:"https://drive.google.com/file/d/1ZSnaLDBgk0t0LmZZmELDm7GSAO68A3BA/view"},
  {id:"sujebi-2026-sw-design-ch02-08",sourceQuestionNo:8,sourcePage:"1-36",questionType:"single_choice",questionText:"User Interface 설계 시 오류 메시지나 경고에 관한 지침으로 가장 거리가 먼 것은?",choices:["메시지는 이해하기 쉬워야 한다.","오류로부터 회복을 위한 구체적인 설명이 제공되어야 한다.","오류로 인해 발생할 수 있는 부정적인 내용을 적극적으로 사용자들에게 알려야 한다.","소리나 색의 사용을 줄이고 텍스트로만 전달하도록 한다."],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"오류 메시지나 경고는 텍스트뿐 아니라 소리나 색 등을 적절히 사용해 쉽게 인지할 수 있게 해야 한다.",finalKey:"오류 경고 = 텍스트만 고집하지 말고 소리·색도 활용",sourceImageUrl:"https://drive.google.com/file/d/1ZSnaLDBgk0t0LmZZmELDm7GSAO68A3BA/view"},
  {id:"sujebi-2026-sw-design-ch02-09",sourceQuestionNo:9,sourcePage:"1-37",questionType:"single_choice",questionText:"사용자 인터페이스를 설계할 경우 고려해야 할 가이드라인과 가장 거리가 먼 것은?",choices:["심미성을 사용성보다 우선하여 설계해야 한다.","효율성을 높이게 설계해야 한다.","발생하는 오류를 쉽게 수정할 수 있어야 한다.","사용자에게 피드백을 제공해야 한다."],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"UI 설계에서는 심미성보다 사용성을 우선적으로 고려해야 한다.",finalKey:"UI = 심미성보다 사용성 우선",sourceImageUrl:"https://drive.google.com/file/d/1B5o4KSvB992rP6ePDFG7_9g11bbGIoM3/view"},
  {id:"sujebi-2026-sw-design-ch02-10",sourceQuestionNo:10,sourcePage:"1-37",questionType:"single_choice",questionText:"UI의 설계 지침으로 틀린 것은?",choices:["이해하기 편하고 쉽게 사용할 수 있는 환경을 제공해야 한다.","주요 기능을 메인 화면에 노출하여 조작이 쉽도록 하여야 한다.","치명적인 오류에 대한 부정적인 사항은 사용자가 인지할 수 없도록 한다.","사용자의 직무, 연령, 성별 등 다양한 계층을 수용하여야 한다."],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"치명적 오류나 부정적 결과는 사용자가 정확히 인지할 수 있도록 명확하게 알려야 한다.",finalKey:"치명적 오류는 숨기지 말고 명확히 알림",sourceImageUrl:"https://drive.google.com/file/d/1B5o4KSvB992rP6ePDFG7_9g11bbGIoM3/view"},
  {id:"sujebi-2026-sw-design-ch02-11",sourceQuestionNo:11,sourcePage:"1-37",questionType:"single_choice",questionText:"UI의 종류로 멀티 터치(Multi-touch), 동작 인식(Gesture Recognition) 등 사용자의 자연스러운 움직임을 인식하여 서로 주고받는 정보를 제공하는 사용자 인터페이스는?",choices:["GUI(Graphical User Interface)","OUI(Organic Interface)","NUI(Natural User Interface)","CLI(Command Line Interface)"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"NUI는 멀티터치, 동작 인식 등 사용자의 자연스러운 움직임을 인식해 상호작용하는 인터페이스다.",finalKey:"멀티터치·제스처 = NUI",sourceImageUrl:"https://drive.google.com/file/d/1B5o4KSvB992rP6ePDFG7_9g11bbGIoM3/view"},
  {id:"sujebi-2026-sw-design-ch02-12",sourceQuestionNo:12,sourcePage:"1-37",questionType:"single_choice",questionText:"UI와 관련된 기본 개념 중 하나로, 시스템의 상태와 사용자의 지시에 대한 효과를 보여주어 사용자가 명령에 대한 진행 상황과 표시된 내용을 해석할 수 있도록 도와주는 것은?",choices:["Feedback","Posture","Module","Hash"],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"Feedback은 시스템 상태와 사용자 명령의 진행 상황을 알려 사용자가 결과를 해석할 수 있도록 돕는다.",finalKey:"시스템 상태·진행상황 알림 = Feedback",sourceImageUrl:"https://drive.google.com/file/d/1B5o4KSvB992rP6ePDFG7_9g11bbGIoM3/view"},
  {id:"sujebi-2026-sw-design-ch02-13",sourceQuestionNo:13,sourcePage:"1-38",questionType:"single_choice",questionText:"다음 중 UI(User Interface) 제스처가 아닌 것은?",choices:["프레스(Press)","드래그(Drag)","플릭(Flick)","프로세스(Process)"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"대표 UI 제스처에는 탭, 더블탭, 프레스, 플릭, 스와이프, 팬, 드래그, 핀치, 로테이트 등이 있다. Process는 제스처가 아니다.",finalKey:"UI 제스처 ≠ Process",sourceImageUrl:"https://drive.google.com/file/d/1PRn07fwVtYCsUbgkvClRVDZXMmklrO3Z/view"},
  {id:"sujebi-2026-sw-design-ch02-14",sourceQuestionNo:14,sourcePage:"1-38",questionType:"single_choice",questionText:"디자인, 사용 방법 설명, 평가 등을 위해 실제 화면과 유사하게 만든 정적인 형태의 모형으로, 시각적으로만 구성요소를 배치하고 일반적으로 실제 구현은 하지 않는 UI 설계 도구는?",choices:["스토리보드(Storyboard)","목업(Mockup)","프로토타입(Prototype)","유스케이스(Usecase)"],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"목업은 실제 화면과 유사한 정적인 모형으로 시각적 구성요소를 배치하지만 일반적으로 실제 기능 구현은 하지 않는다.",finalKey:"정적 화면 모형 = Mockup",sourceImageUrl:"https://drive.google.com/file/d/1PRn07fwVtYCsUbgkvClRVDZXMmklrO3Z/view"},
  {id:"sujebi-2026-sw-design-ch02-15",sourceQuestionNo:15,sourcePage:"1-38",questionType:"single_choice",questionText:"UI 화면 설계를 위해서 정책이나 프로세스 및 콘텐츠의 구성, 와이어 프레임(UI, UX), 기능에 대한 정의, 데이터베이스의 연동 등 구축하는 서비스를 위한 대부분 정보가 수록된 문서는?",choices:["와이어 프레임(Wireframe)","스토리보드(Storyboard)","프로토타입(Prototype)","유스케이스(Usecase)"],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"스토리보드는 정책, 프로세스, 콘텐츠 구성, 와이어프레임, 기능 정의, DB 연동 등 서비스 구축에 필요한 정보를 종합적으로 담는 설계 산출물이다.",finalKey:"UI 구축 정보 종합 문서 = Storyboard",sourceImageUrl:"https://drive.google.com/file/d/1PRn07fwVtYCsUbgkvClRVDZXMmklrO3Z/view"}
];

const currentIdBeforeCh02_01_15 = state.currentRoundIds?.[state.currentIndex];
const knownCh02_01_15 = new Set(QUESTIONS.map(q => q.id));
const addCh02_01_15 = CH02_QUESTIONS_01_15.filter(q => !knownCh02_01_15.has(q.id));
if (addCh02_01_15.length) QUESTIONS.push(...addCh02_01_15);
const orderedCh02 = QUESTIONS.filter(q => q.id.startsWith("sujebi-2026-sw-design-ch02-")).sort((a,b) => a.sourceQuestionNo - b.sourceQuestionNo);
const orderedCh03plus = QUESTIONS.filter(q => !q.id.startsWith("sujebi-2026-sw-design-ch02-"));
QUESTIONS.splice(0, QUESTIONS.length, ...orderedCh02, ...orderedCh03plus);
if (state.mode !== "weak") {
  state.currentRoundIds = QUESTIONS.map(q => q.id);
  const preserved = state.currentRoundIds.indexOf(currentIdBeforeCh02_01_15);
  state.currentIndex = preserved >= 0 ? preserved : Math.min(state.currentIndex || 0, state.currentRoundIds.length - 1);
  saveState();
}
if (typeof renderDashboardV01 === "function") renderDashboardV01();