const CH03_QUESTIONS_36_51 = [
  {id:"sujebi-2026-sw-design-ch03-36",sourceQuestionNo:36,sourcePage:"1-49",questionType:"single_choice",questionText:"다음 중 가장 높은 응집도(Cohesion)에 해당하는 것은?",choices:["순차적 응집도(Sequential Cohesion)","시간적 응집도(Temporal Cohesion)","논리적 응집도(Logical Cohesion)","절차적 응집도(Procedural Cohesion)"],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"응집도는 우연적 < 논리적 < 시간적 < 절차적 < 통신적 < 순차적 < 기능적 순으로 높아진다.",finalKey:"응집도: 우논시절통순기",sourceImageUrl:"https://drive.google.com/file/d/10CB7flkTi_Sw9ZQa7u4rUH51_ZzKuv_M/view"},
  {id:"sujebi-2026-sw-design-ch03-37",sourceQuestionNo:37,sourcePage:"1-49",questionType:"single_choice",questionText:"응집도가 가장 낮은 것은?",choices:["기능적 응집도","시간적 응집도","절차적 응집도","우연적 응집도"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"우연적 응집도(Coincidental Cohesion)가 가장 낮은 응집도이다.",finalKey:"가장 낮은 응집도 = 우연적",sourceImageUrl:"https://drive.google.com/file/d/10CB7flkTi_Sw9ZQa7u4rUH51_ZzKuv_M/view"},
  {id:"sujebi-2026-sw-design-ch03-38",sourceQuestionNo:38,sourcePage:"1-49",questionType:"single_choice",questionText:"서로 간에 어떠한 의미 있는 연관 관계도 지니지 않은 기능 요소로 구성되고, 서로 다른 상위 모듈에 의해 호출되어 처리상의 연관성이 없는 서로 다른 기능을 수행하는 경우의 응집도는?",choices:["Functional Cohesion","Sequential Cohesion","Logical Cohesion","Coincidental Cohesion"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"서로 의미 있는 연관이 없는 요소들이 우연히 한 모듈에 모인 경우는 우연적 응집도이다.",finalKey:"연관성 없이 우연히 모임 = Coincidental",sourceImageUrl:"https://drive.google.com/file/d/10CB7flkTi_Sw9ZQa7u4rUH51_ZzKuv_M/view"},
  {id:"sujebi-2026-sw-design-ch03-39",sourceQuestionNo:39,sourcePage:"1-49",questionType:"single_choice",questionText:"다음 중 응집도가 가장 높은 것은?",choices:["절차적 응집도","순차적 응집도","우연적 응집도","논리적 응집도"],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"제시된 선택지 중 순차적 응집도가 가장 높은 수준이다.",finalKey:"절차 < 순차",sourceImageUrl:"https://drive.google.com/file/d/10CB7flkTi_Sw9ZQa7u4rUH51_ZzKuv_M/view"},
  {id:"sujebi-2026-sw-design-ch03-40",sourceQuestionNo:40,sourcePage:"1-49",questionType:"single_choice",questionText:"다음 중 가장 강한 응집도(Cohesion)는?",choices:["Sequential Cohesion","Procedural Cohesion","Logical Cohesion","Coincidental Cohesion"],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"선택지 중 순차적 응집도가 가장 강하다.",finalKey:"Sequential > Procedural > Logical > Coincidental",sourceImageUrl:"https://drive.google.com/file/d/10CB7flkTi_Sw9ZQa7u4rUH51_ZzKuv_M/view"},
  {id:"sujebi-2026-sw-design-ch03-41",sourceQuestionNo:41,sourcePage:"1-50",questionType:"single_choice",questionText:"모듈 내 구성요소들이 서로 다른 기능을 같은 시간대에 함께 실행하는 경우의 응집도(Cohesion)는?",choices:["Temporal Cohesion","Logical Cohesion","Coincidental Cohesion","Sequential Cohesion"],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"특정 시점에 함께 처리되어야 하는 활동들을 묶은 것은 시간적 응집도이다.",finalKey:"같은 시간대에 함께 실행 = Temporal",sourceImageUrl:"https://drive.google.com/file/d/1vs9Jo0m9I9CL8YwjjttyGObt324NQ2G8/view"},
  {id:"sujebi-2026-sw-design-ch03-42",sourceQuestionNo:42,sourcePage:"1-50",questionType:"single_choice",questionText:"다음 중 소프트웨어 아키텍처 4+1 뷰의 구성요소가 아닌 것은?",choices:["유스케이스 뷰(Use-Case View)","논리 뷰(Logical View)","프로세스 뷰(Process View)","클래스 뷰(Class View)"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"4+1 뷰는 유스케이스, 논리, 프로세스, 구현, 배포 뷰로 구성된다.",finalKey:"4+1 = 유논프구배",sourceImageUrl:"https://drive.google.com/file/d/1vs9Jo0m9I9CL8YwjjttyGObt324NQ2G8/view"},
  {id:"sujebi-2026-sw-design-ch03-43",sourceQuestionNo:43,sourcePage:"1-50",questionType:"single_choice",questionText:"동일한 입력과 출력을 사용하여 다른 기능을 수행하는 활동들이 모여 있을 경우의 응집도 유형은?",choices:["논리적 응집도","절차적 응집도","시간적 응집도","교환적 응집도"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"동일한 입력과 출력을 사용하면서 서로 다른 기능을 수행하는 요소들이 모인 것은 교환적(통신적) 응집도이다.",finalKey:"같은 입력·출력 공유 = 교환적/통신적 응집도",sourceImageUrl:"https://drive.google.com/file/d/1vs9Jo0m9I9CL8YwjjttyGObt324NQ2G8/view"},
  {id:"sujebi-2026-sw-design-ch03-44",sourceQuestionNo:44,sourcePage:"1-50",questionType:"single_choice",questionText:"물리적 시스템을 구성하고 있는 각 부분들의 분산 형태와 설치에 초점을 두는 소프트웨어 아키텍처 4+1 뷰는?",choices:["Usecase View","Deployment View","Logical View","Process View"],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"배포 뷰는 물리적 컴퓨터와 노드에 소프트웨어 구성요소가 어떻게 배치되는지를 보여준다.",finalKey:"물리적 분산·설치 = Deployment View",sourceImageUrl:"https://drive.google.com/file/d/1vs9Jo0m9I9CL8YwjjttyGObt324NQ2G8/view"},
  {id:"sujebi-2026-sw-design-ch03-45",sourceQuestionNo:45,sourcePage:"1-51",questionType:"single_choice",questionText:"대상 자료의 물리적인 수치인 길이, 넓이, 용량 등을 표시한 코드는 무엇인가?",choices:["Mnemonic Code","Block Code","Significant Digit Code","Decimal Code"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"표의 숫자 코드는 대상의 물리적 수치인 길이·넓이·용량 등을 코드에 반영하는 Significant Digit Code이다.",finalKey:"물리적 수치 반영 코드 = Significant Digit Code",sourceImageUrl:"https://drive.google.com/file/d/1Myah-XpAv9Rddc49pPaaYDmenDitpc6i/view"},
  {id:"sujebi-2026-sw-design-ch03-46",sourceQuestionNo:46,sourcePage:"1-51",questionType:"single_choice",questionText:"다음 결합도의 종류에 대한 설명 중 틀린 것은?",choices:["Content Coupling: 다른 모듈 내부의 변수나 기능을 다른 모듈에서 사용하는 경우의 결합도이다.","Stamp Coupling: 파라미터가 아닌 모듈 밖에 선언된 전역 변수를 참조하고 갱신하는 식으로 상호 작용하는 경우의 결합도이다.","Data Coupling: 모듈 간 인터페이스로 전달되는 파라미터를 통해서만 상호 작용이 일어나는 경우의 결합도이다.","Control Coupling: 어떤 모듈이 다른 모듈의 내부 논리 조직을 제어하기 위해 제어 신호를 이용하여 통신하는 경우의 결합도이다."],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"전역 변수를 공유하는 설명은 공통(Common) 결합도이다. 스탬프 결합도는 자료구조나 객체 등 복합 자료구조가 모듈 간 인터페이스로 전달되는 경우다.",finalKey:"전역 변수 공유 = Common Coupling",sourceImageUrl:"https://drive.google.com/file/d/1Myah-XpAv9Rddc49pPaaYDmenDitpc6i/view"},
  {id:"sujebi-2026-sw-design-ch03-47",sourceQuestionNo:47,sourcePage:"1-51",questionType:"single_choice",questionText:"분리된 컴포넌트들로 이루어진 분산 시스템에서 사용되며, 컴포넌트들이 원격 서비스 호출을 통해 상호 작용할 수 있도록 중개 역할을 수행하는 아키텍처 패턴은?",choices:["마스터-슬레이브(Master-Slave) 패턴","클라이언트-서버(Client-Server) 패턴","파이프-필터(Pipe-Filter) 패턴","브로커(Broker) 패턴"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"Broker 패턴은 분산 환경에서 컴포넌트 간 통신을 중개하고 원격 서비스 호출 구조를 제공한다.",finalKey:"분산 컴포넌트 원격 호출 중개 = Broker",sourceImageUrl:"https://drive.google.com/file/d/1Myah-XpAv9Rddc49pPaaYDmenDitpc6i/view"},
  {id:"sujebi-2026-sw-design-ch03-48",sourceQuestionNo:48,sourcePage:"1-51",questionType:"single_choice",questionText:"MVC 아키텍처 패턴에서 사용자 입력을 처리하고 모델과 뷰 사이에서 전달자 역할을 수행하는 구성요소는?",choices:["Model","View","Controller","Observer"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"Controller는 사용자 요청을 입력받아 처리하고 Model과 View 사이의 전달자 역할을 한다.",finalKey:"사용자 입력 처리 + Model/View 중재 = Controller",sourceImageUrl:"https://drive.google.com/file/d/1Myah-XpAv9Rddc49pPaaYDmenDitpc6i/view"},
  {id:"sujebi-2026-sw-design-ch03-49",sourceQuestionNo:49,sourcePage:"1-52",questionType:"single_choice",questionText:"객체에 대한 특성을 설명한 것으로 가장 옳지 않은 것은?",choices:["객체마다 각각의 상태를 갖고 있다.","식별성을 가진다.","행위에 대하여 그 특징을 나타낼 수 있다.","일정한 기억장소를 가지고 있지 않다."],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"객체는 상태와 식별성, 행위를 가지며 메모리에 할당되는 실체이므로 일정한 기억장소를 가진다고 본다.",finalKey:"객체 = 상태·식별성·행위·메모리 공간",sourceImageUrl:"https://drive.google.com/file/d/1bMKz1VbtWs8dqWIe_3GYG5EYuwzZtVws/view"},
  {id:"sujebi-2026-sw-design-ch03-50",sourceQuestionNo:50,sourcePage:"1-52",questionType:"single_choice",questionText:"객체에게 어떤 행위를 하도록 지시하는 명령은?",choices:["클래스(Class)","인스턴스(Instance)","객체(Object)","메시지(Message)"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"메시지는 객체에게 특정 행위를 하도록 요청하거나 지시하는 방법이다.",finalKey:"객체에게 행위를 지시 = Message",sourceImageUrl:"https://drive.google.com/file/d/1bMKz1VbtWs8dqWIe_3GYG5EYuwzZtVws/view"},
  {id:"sujebi-2026-sw-design-ch03-51",sourceQuestionNo:51,sourcePage:"1-52",questionType:"single_choice",questionText:"코드 내부 데이터와 메서드를 숨기고 공개 인터페이스를 통해서만 접근이 가능하도록 하여 유지보수와 소프트웨어 확장 시 오류를 최소화하는 기법은?",choices:["추상화(Abstraction)","상속성(Inheritance)","정보 은닉(Information Hiding)","다형성(Polymorphism)"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"정보 은닉은 내부 데이터와 메서드를 숨기고 공개 인터페이스를 통해서만 접근하도록 하여 변경 영향을 줄인다.",finalKey:"내부 숨김 + 공개 인터페이스 접근 = Information Hiding",sourceImageUrl:"https://drive.google.com/file/d/1bMKz1VbtWs8dqWIe_3GYG5EYuwzZtVws/view"}
];

const currentIdBeforeCh03_36_51 = state.currentRoundIds?.[state.currentIndex];
const ch03Known36_51 = new Set(QUESTIONS.map(q => q.id));
const ch03Add36_51 = CH03_QUESTIONS_36_51.filter(q => !ch03Known36_51.has(q.id));
if (ch03Add36_51.length) QUESTIONS.push(...ch03Add36_51);
const orderedCh03_36 = QUESTIONS.filter(q => q.id.startsWith("sujebi-2026-sw-design-ch03-")).sort((a,b) => a.sourceQuestionNo - b.sourceQuestionNo);
const orderedNonCh03_36 = QUESTIONS.filter(q => !q.id.startsWith("sujebi-2026-sw-design-ch03-"));
QUESTIONS.splice(0, QUESTIONS.length, ...orderedCh03_36, ...orderedNonCh03_36);
if (state.mode !== "weak") {
  state.currentRoundIds = QUESTIONS.map(q => q.id);
  const preserved = state.currentRoundIds.indexOf(currentIdBeforeCh03_36_51);
  state.currentIndex = preserved >= 0 ? preserved : Math.min(state.currentIndex || 0, state.currentRoundIds.length - 1);
  saveState();
}
if (typeof renderDashboardV01 === "function") renderDashboardV01();
