const CH01_QUESTIONS_49_70 = [
  {id:"sujebi-2026-sw-design-ch01-49",sourceQuestionNo:49,sourcePage:"1-29",questionType:"single_choice",questionText:"UML의 상태 다이어그램(State Diagram)의 구성요소 중 객체의 전이를 유발하는 자극으로 상태의 변화를 주는 현상은 무엇인가?",choices:["상태(State)","이벤트(Event)","전이 조건(Transition Condition)","전이(Transition)"],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"이벤트(Event)는 객체의 전이를 유발해 상태 변화를 일으키는 자극이나 현상이다.",finalKey:"상태 변화를 유발하는 자극 = Event",sourceImageUrl:"https://drive.google.com/file/d/1_fksOUlrEd5yh2rZ60VFmcB9jkdfPhzS/view"},
  {id:"sujebi-2026-sw-design-ch01-50",sourceQuestionNo:50,sourcePage:"1-29",questionType:"single_choice",questionText:"다음 중 동적 다이어그램이 아닌 것은?",choices:["State Diagram","Deployment Diagram","Activity Diagram","Timing Diagram"],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"Deployment Diagram은 정적 구조를 표현하는 구조적 다이어그램이다. State, Activity, Timing은 행위적/동적 다이어그램이다.",finalKey:"Deployment = 정적 다이어그램",sourceImageUrl:"https://drive.google.com/file/d/1_fksOUlrEd5yh2rZ60VFmcB9jkdfPhzS/view"},
  {id:"sujebi-2026-sw-design-ch01-51",sourceQuestionNo:51,sourcePage:"1-29",questionType:"single_choice",questionText:"XP에 대한 설명으로 올바르지 않은 것은?",choices:["고객과 직접 대면하며 요구사항을 이야기하기 위해 사용자 스토리(User Story)를 활용할 수 있다.","기존의 방법론에 비해 실용성(Pragmatism)을 강조한 것이라고 볼 수 있다.","페어 프로그래밍은 혼자 할 때보다 더 오류가 적은 프로그램을 만들 수 있다.","재사용성을 위해 단순함을 포기해야 한다."],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"XP는 단순성(Simplicity)을 핵심 가치로 두며 재사용성을 위해 단순함을 포기하지 않는다.",finalKey:"XP 핵심 = 단순성, 포기하지 않음",sourceImageUrl:"https://drive.google.com/file/d/1_fksOUlrEd5yh2rZ60VFmcB9jkdfPhzS/view"},
  {id:"sujebi-2026-sw-design-ch01-52",sourceQuestionNo:52,sourcePage:"1-29",questionType:"single_choice",questionText:"UML의 활동 다이어그램에 대한 설명으로 올바른 것은?",choices:["시스템이 어떤 기능을 수행하는지를 객체의 처리 로직이나 조건에 따른 처리의 흐름으로 순서대로 표현하는 다이어그램","동작에 참여하는 객체들이 주고받는 메시지를 표현하는데, 메시지뿐만 아니라 객체 간의 연관까지 표현하는 다이어그램","객체 간 상호 작용을 메시지 흐름으로 표현하는 다이어그램","하나의 객체가 자신이 속한 클래스의 상태 변화 혹은 다른 객체와의 상호 작용에 따라 상태가 어떻게 변화하는지 표현하는 다이어그램"],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"Activity Diagram은 시스템의 기능 수행 흐름, 처리 로직, 조건에 따른 순서를 표현한다.",finalKey:"처리 로직·조건에 따른 흐름 = Activity Diagram",sourceImageUrl:"https://drive.google.com/file/d/1_fksOUlrEd5yh2rZ60VFmcB9jkdfPhzS/view"},
  {id:"sujebi-2026-sw-design-ch01-53",sourceQuestionNo:53,sourcePage:"1-30",questionType:"single_choice",questionText:"UML의 관계 중 한 객체가 다른 객체에 오퍼레이션을 수행하도록 지정하는 관계를 표현하고, 사물에서 기능 쪽으로 속이 빈 점선 화살표를 연결하여 표현하는 관계는?",choices:["연관(Association) 관계","의존(Dependency) 관계","일반화(Generalization) 관계","실체화(Realization) 관계"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"실체화(Realization)는 한 객체가 다른 객체에 오퍼레이션 수행을 지정하는 관계이며 속이 빈 점선 화살표로 표현한다.",finalKey:"속 빈 점선 화살표·오퍼레이션 지정 = Realization",sourceImageUrl:"https://drive.google.com/file/d/1_LL70h7S6iN7KKWJ4K38NotonS3dP8H9/view"},
  {id:"sujebi-2026-sw-design-ch01-54",sourceQuestionNo:54,sourcePage:"1-30",questionType:"single_choice",questionText:"다음 중 요구분석 단계에 대한 설명으로 올바르지 않은 것은?",choices:["요구분석은 사용자의 요구를 추출하여 목표를 정하고 어떤 방식으로 해결할 것인지 결정하는 단계이다.","보다 구체적인 명세를 위해 소단위 명세서가 활용될 수 있다.","요구분석 단계에서 동적 분석과 정적 분석을 통해 잘못된 요구사항을 걸러내야 한다.","모델링 표기를 위해 DFD(Data Flow Diagram), UML 다이어그램, E-R 다이어그램을 사용한다."],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"정적 분석과 동적 분석은 설계·구현·테스트 단계에서 수행하며 요구분석 단계의 대표 활동으로 보지 않는다.",finalKey:"정적·동적 분석 = 요구분석 단계의 대표 활동 아님",sourceImageUrl:"https://drive.google.com/file/d/1_LL70h7S6iN7KKWJ4K38NotonS3dP8H9/view"},
  {id:"sujebi-2026-sw-design-ch01-55",sourceQuestionNo:55,sourcePage:"1-31",questionType:"single_choice",questionText:"유스케이스 다이어그램의 구성요소가 아닌 것은?",choices:["유스케이스(Usecase)","액터(Actor)","시스템(System)","클래스(Class)"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"유스케이스 다이어그램의 주요 구성요소는 유스케이스, 액터, 시스템이다. 클래스는 클래스 다이어그램의 요소다.",finalKey:"Use Case 구성요소 ≠ Class",sourceImageUrl:"https://drive.google.com/file/d/1NdkukRk0EYAJKwbVnalBmAACniH4xYgk/view"},
  {id:"sujebi-2026-sw-design-ch01-56",sourceQuestionNo:56,sourcePage:"1-31",questionType:"single_choice",questionText:"스크럼(Scrum)에서 해당 스프린트가 계획대로 나아가고 있는지, 목표 달성을 위해 팀 차원의 조정이 필요한지를 확인하고 작업 진행 상황을 점검하는 것은?",choices:["스프린트 회고","스크럼 미팅","백로그","버전 관리"],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"스크럼 미팅은 팀원이 매일 짧게 모여 스프린트 진행 상황을 공유하고 조정하는 회의다.",finalKey:"매일 진행상황 공유·조정 = Scrum Meeting",sourceImageUrl:"https://drive.google.com/file/d/1NdkukRk0EYAJKwbVnalBmAACniH4xYgk/view"},
  {id:"sujebi-2026-sw-design-ch01-57",sourceQuestionNo:57,sourcePage:"1-31",questionType:"single_choice",questionText:"다음 중 스크럼(Scrum)에서 제품 책임자(Product Owner)의 역할로 가장 적절한 것은?",choices:["팀의 기술적 장애를 해결하고 스프린트 회고를 주도한다.","스크럼 프로세스를 따르고 팀이 스크럼을 효과적으로 활용할 수 있도록 보장하는 역할을 수행한다.","이해관계자의 의견을 종합하여 제품에 대한 요구사항을 작성한다.","스크럼 팀이 스크럼 원칙과 규칙을 잘 따르도록 안내한다."],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"Product Owner는 이해관계자의 의견을 종합하여 제품 요구사항과 백로그를 관리하고 우선순위를 조정한다.",finalKey:"Product Owner = 요구사항·제품 백로그 책임",sourceImageUrl:"https://drive.google.com/file/d/1NdkukRk0EYAJKwbVnalBmAACniH4xYgk/view"},
  {id:"sujebi-2026-sw-design-ch01-58",sourceQuestionNo:58,sourcePage:"1-31",questionType:"single_choice",questionText:"객체들이 어떻게 상호 동작하는지를 메시지 순서에 초점을 맞춰 나타내고, 어떠한 작업이 객체 간에 발생하는지를 시간 순서에 따라 보여주는 UML 다이어그램은?",choices:["클래스(Class) 다이어그램","순차(Sequence) 다이어그램","배치(Deployment) 다이어그램","컴포넌트(Component) 다이어그램"],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"Sequence Diagram은 객체 간 메시지 교환을 시간 순서에 따라 표현한다.",finalKey:"메시지 순서·시간 흐름 = Sequence Diagram",sourceImageUrl:"https://drive.google.com/file/d/1NdkukRk0EYAJKwbVnalBmAACniH4xYgk/view"},
  {id:"sujebi-2026-sw-design-ch01-59",sourceQuestionNo:59,sourcePage:"1-32",questionType:"single_choice",questionText:"CASE(Computer Aided Software Engineering)에 대한 설명으로 가장 옳지 않은 것은?",choices:["프로그램의 구현과 유지보수 작업만을 중심으로 소프트웨어 생산성 문제를 해결한다.","소프트웨어 생명주기의 전체 단계를 연결해 주고 자동화해 주는 통합된 도구를 제공한다.","개발 과정의 속도를 향상시킨다.","소프트웨어 부품의 재사용을 가능하게 한다."],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"CASE는 구현·유지보수만이 아니라 소프트웨어 생명주기 전체 또는 일부를 자동화하고 연결한다.",finalKey:"CASE = 생명주기 전체/일부 자동화, 구현·유지보수만 아님",sourceImageUrl:"https://drive.google.com/file/d/1IalLKjcL_d8BhyI9BZMbK3TJFRrUkt2l/view"},
  {id:"sujebi-2026-sw-design-ch01-60",sourceQuestionNo:60,sourcePage:"1-32",questionType:"single_choice",questionText:"소프트웨어, 하드웨어, 데이터베이스, 테스트 등을 통합하여 소프트웨어를 개발하는 환경을 조성한다는 의미를 가진 개념은?",choices:["CAD","CAI","CAM","CASE"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"CASE는 소프트웨어 개발을 지원하기 위해 관련 도구와 환경을 통합하는 개념이다.",finalKey:"SW 개발 통합환경 = CASE",sourceImageUrl:"https://drive.google.com/file/d/1IalLKjcL_d8BhyI9BZMbK3TJFRrUkt2l/view"},
  {id:"sujebi-2026-sw-design-ch01-61",sourceQuestionNo:61,sourcePage:"1-32",questionType:"single_choice",questionText:"다음 중 상위 CASE 도구가 지원하는 중요 기능으로 볼 수 없는 것은?",choices:["모델들 사이의 모순 검사 기능","모델의 오류 검증 기능","소스 코드 생성 기능","자료흐름도 작성 기능"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"소스 코드 생성은 하위 CASE 도구의 주요 기능이다. 상위 CASE는 요구분석·설계·모델 검증·다이어그램 작성 등을 지원한다.",finalKey:"소스 코드 생성 = Lower CASE",sourceImageUrl:"https://drive.google.com/file/d/1IalLKjcL_d8BhyI9BZMbK3TJFRrUkt2l/view"},
  {id:"sujebi-2026-sw-design-ch01-62",sourceQuestionNo:62,sourcePage:"1-32",questionType:"single_choice",questionText:"CASE가 갖고 있는 주요 기능이 아닌 것은?",choices:["그래픽 지원","소프트웨어 생명주기 전 단계의 연결","언어 번역","다양한 소프트웨어 개발 모형 지원"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"CASE의 주요 기능에는 그래픽 지원, 생명주기 연결, 개발 모형 지원, 문서 자동화와 협업 등이 있으며 언어 번역은 핵심 기능이 아니다.",finalKey:"CASE 주요 기능 ≠ 언어 번역",sourceImageUrl:"https://drive.google.com/file/d/1IalLKjcL_d8BhyI9BZMbK3TJFRrUkt2l/view"},
  {id:"sujebi-2026-sw-design-ch01-63",sourceQuestionNo:63,sourcePage:"1-33",questionType:"single_choice",questionText:"CASE 도구에 대한 설명으로 거리가 먼 것은?",choices:["소프트웨어 개발 과정의 일부 또는 전체를 자동화하기 위한 도구이다.","표준화된 개발 환경 구축 및 문서 자동화 기능을 제공한다.","작업 과정 및 데이터 공유를 통해 작업자 간의 커뮤니케이션을 증대한다.","2000년대 이후 소개되었으며, 객체 지향 시스템에 한해 효과적으로 활용된다."],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"CASE 도구는 1980년대부터 등장했으며 객체지향 시스템에만 한정되지 않는다.",finalKey:"CASE = 1980년대 등장, 객체지향 전용 아님",sourceImageUrl:"https://drive.google.com/file/d/1cKGQ-c234DMuNEhj1sGGqq8obtKlJWYh/view"},
  {id:"sujebi-2026-sw-design-ch01-64",sourceQuestionNo:64,sourcePage:"1-33",questionType:"single_choice",questionText:"CASE(Computer Aided Software Engineering)에 대한 설명으로 틀린 것은?",choices:["소프트웨어 모듈의 재사용성이 향상된다.","자동화된 기법을 통해 소프트웨어 품질이 향상된다.","소프트웨어 사용자들에게 사용 방법을 신속히 숙지시키기 위해 사용된다.","소프트웨어 유지보수를 간편하게 수행할 수 있다."],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"CASE는 개발자들의 소프트웨어 개발·유지보수 활동을 지원하는 도구이지 최종 사용자 교육을 위한 도구가 아니다.",finalKey:"CASE ≠ 사용자 교육 도구",sourceImageUrl:"https://drive.google.com/file/d/1cKGQ-c234DMuNEhj1sGGqq8obtKlJWYh/view"},
  {id:"sujebi-2026-sw-design-ch01-65",sourceQuestionNo:65,sourcePage:"1-33",questionType:"single_choice",questionText:"CASE(Computer Aided Software Engineering)의 원천 기술이 아닌 것은?",choices:["구조적 기법","프로토타이핑 기술","정보 저장소 기술","일괄처리 기술"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"CASE의 원천 기술에는 구조적 기법, 프로토타이핑, 정보 저장소, 자동 프로그래밍, 분산 처리 등이 있다. 일괄처리는 해당하지 않는다.",finalKey:"CASE 원천기술 ≠ 일괄처리",sourceImageUrl:"https://drive.google.com/file/d/1cKGQ-c234DMuNEhj1sGGqq8obtKlJWYh/view"},
  {id:"sujebi-2026-sw-design-ch01-66",sourceQuestionNo:66,sourcePage:"1-33",questionType:"single_choice",questionText:"다음 중 상위 CASE 도구가 지원하는 주요 기능으로 볼 수 없는 것은?",choices:["모델들 사이의 모순 검사 기능","전체 소스 코드 생성 기능","모델의 오류 검증 기능","자료 흐름도 작성 기능"],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"전체 소스 코드 생성은 하위 CASE의 구현 지원 기능에 해당한다. 상위 CASE는 분석·설계·모델 검증과 다이어그램 작성을 지원한다.",finalKey:"전체 소스 코드 생성 = Upper CASE 아님",sourceImageUrl:"https://drive.google.com/file/d/1cKGQ-c234DMuNEhj1sGGqq8obtKlJWYh/view"},
  {id:"sujebi-2026-sw-design-ch01-67",sourceQuestionNo:67,sourcePage:"1-34",questionType:"single_choice",questionText:"소프트웨어 공학에서 모델링(Modeling)과 관련한 설명으로 틀린 것은?",choices:["개발팀이 응용문제를 이해하는 데 도움을 줄 수 있다.","유지보수 단계에서만 모델링 기법을 활용한다.","개발될 시스템에 대하여 여러 분야의 엔지니어들이 공통된 개념을 공유하는 데 도움을 준다.","절차적인 프로그램을 위한 자료 흐름도는 프로세스 위주의 모델링 방법이다."],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"모델링은 유지보수뿐 아니라 분석, 설계, 구현 등 소프트웨어 개발 전반에서 활용된다.",finalKey:"모델링 = 개발 전반에서 활용",sourceImageUrl:"https://drive.google.com/file/d/1YUDq2f3NkZSzv0hVXlCBzNNAOYOpm2Wv/view"},
  {id:"sujebi-2026-sw-design-ch01-68",sourceQuestionNo:68,sourcePage:"1-34",questionType:"single_choice",questionText:"요구사항 관리 도구의 필요성으로 틀린 것은?",choices:["요구사항 변경으로 인한 비용 편익 분석","기존 시스템과 신규 시스템의 성능 비교","요구사항 변경의 추적","요구사항 변경에 따른 영향 평가"],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"요구사항 관리 도구는 변경 추적, 영향 평가, 비용·편익 분석 등을 지원한다. 기존/신규 시스템 성능 비교는 직접적인 필요성이 아니다.",finalKey:"요구관리 도구 ≠ 기존·신규 시스템 성능 비교",sourceImageUrl:"https://drive.google.com/file/d/1YUDq2f3NkZSzv0hVXlCBzNNAOYOpm2Wv/view"},
  {id:"sujebi-2026-sw-design-ch01-69",sourceQuestionNo:69,sourcePage:"1-34",questionType:"single_choice",questionText:"소프트웨어 모델링과 관련한 설명으로 틀린 것은?",choices:["모델링 작업의 결과물은 다른 모델링 작업에 영향을 줄 수 없다.","구조적 방법론에서는 DFD(Data Flow Diagram), DD(Data Dictionary) 등을 사용하여 요구사항의 결과를 표현한다.","객체 지향 방법론에서는 UML 표기법을 사용한다.","소프트웨어 모델을 사용할 경우 개발될 소프트웨어에 대한 이해도 및 이해 당사자 간의 의사소통 향상에 도움이 된다."],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"모델링 산출물은 서로 연계되므로 한 모델링 작업의 결과가 다른 모델링 작업에 영향을 줄 수 있다.",finalKey:"모델링 산출물은 서로 영향·연계됨",sourceImageUrl:"https://drive.google.com/file/d/1YUDq2f3NkZSzv0hVXlCBzNNAOYOpm2Wv/view"},
  {id:"sujebi-2026-sw-design-ch01-70",sourceQuestionNo:70,sourcePage:"1-34",questionType:"single_choice",questionText:"소프트웨어 개발에 이용되는 모델(Model)에 대한 설명 중 거리가 먼 것은?",choices:["모델은 개발 대상을 추상화하고 기호나 그림 등으로 시각적으로 표현한다.","모델을 통해 소프트웨어에 대한 이해도를 향상시킬 수 있다.","모델을 통해 이해 당사자 간의 의사소통이 향상된다.","모델링을 통해 향후 개발될 시스템의 유추는 불가능하다."],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"모델링은 시스템을 추상화하여 문제 상황을 이해하고 해결책을 설명하며 향후 개발될 시스템을 유추하는 데 활용할 수 있다.",finalKey:"모델링 → 향후 시스템 유추 가능",sourceImageUrl:"https://drive.google.com/file/d/1YUDq2f3NkZSzv0hVXlCBzNNAOYOpm2Wv/view"}
];

const currentIdBeforeCh01_49_70 = state.currentRoundIds?.[state.currentIndex];
const knownCh01_49_70 = new Set(QUESTIONS.map(q => q.id));
const addCh01_49_70 = CH01_QUESTIONS_49_70.filter(q => !knownCh01_49_70.has(q.id));
if (addCh01_49_70.length) QUESTIONS.push(...addCh01_49_70);
const orderedCh01 = QUESTIONS.filter(q => q.id.startsWith("sujebi-2026-sw-design-ch01-")).sort((a,b) => a.sourceQuestionNo - b.sourceQuestionNo);
const orderedNonCh01 = QUESTIONS.filter(q => !q.id.startsWith("sujebi-2026-sw-design-ch01-"));
QUESTIONS.splice(0, QUESTIONS.length, ...orderedCh01, ...orderedNonCh01);
if (state.mode !== "weak") {
  state.currentRoundIds = QUESTIONS.map(q => q.id);
  const preserved = state.currentRoundIds.indexOf(currentIdBeforeCh01_49_70);
  state.currentIndex = preserved >= 0 ? preserved : Math.min(state.currentIndex || 0, state.currentRoundIds.length - 1);
  saveState();
}
if (typeof renderDashboardV01 === "function") renderDashboardV01();