const CH03_QUESTIONS_23_35 = [
  {id:"sujebi-2026-sw-design-ch03-23",sourceQuestionNo:23,sourcePage:"1-45",questionType:"single_choice",questionText:"소프트웨어 모듈화의 장점이 아닌 것은?",choices:["오류의 파급 효과를 최소화한다.","기능의 분리가 가능하여 인터페이스가 복잡하다.","모듈의 재사용 가능으로 개발과 유지보수가 용이하다.","프로그램의 효율적인 관리가 가능하다."],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"모듈화는 기능 분리와 독립성을 높여 인터페이스를 단순하게 하고 유지보수와 재사용을 쉽게 한다. 인터페이스가 복잡해진다는 설명은 장점이 아니다.",finalKey:"모듈화 → 인터페이스 단순·재사용·유지보수 용이",sourceImageUrl:"https://drive.google.com/file/d/12dtESEvFhVCsPiklKcOH5Lv2QHcR14nM/view"},
  {id:"sujebi-2026-sw-design-ch03-24",sourceQuestionNo:24,sourcePage:"1-45",questionType:"single_choice",questionText:"모듈화(Modularity)와 관련한 설명으로 틀린 것은?",choices:["시스템을 모듈로 분할하면 각각의 모듈을 별개로 만들고 수정할 수 있기 때문에 좋은 구조가 된다.","응집도는 모듈과 모듈 사이의 상호의존 또는 연관 정도를 의미한다.","모듈 간의 결합도가 약해야 독립적인 모듈이 될 수 있다.","모듈 내 구성요소 간의 응집도가 강해야 좋은 모듈 설계이다."],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"모듈과 모듈 사이의 상호의존·연관 정도는 결합도다. 응집도는 한 모듈 내부 구성요소 간의 관련 정도를 뜻한다.",finalKey:"모듈 사이 = 결합도 / 모듈 내부 = 응집도",sourceImageUrl:"https://drive.google.com/file/d/12dtESEvFhVCsPiklKcOH5Lv2QHcR14nM/view"},
  {id:"sujebi-2026-sw-design-ch03-25",sourceQuestionNo:25,sourcePage:"1-45",questionType:"single_choice",questionText:"공통모듈의 재사용 범위에 따른 분류가 아닌 것은?",choices:["컴포넌트 재사용","더미 코드 재사용","함수와 객체 재사용","애플리케이션 재사용"],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"공통모듈 재사용은 함수/객체, 컴포넌트, 애플리케이션 단위 등으로 분류할 수 있다. 더미 코드 재사용은 해당 분류가 아니다.",finalKey:"재사용 범위 = 함수·객체 / 컴포넌트 / 애플리케이션",sourceImageUrl:"https://drive.google.com/file/d/12dtESEvFhVCsPiklKcOH5Lv2QHcR14nM/view"},
  {id:"sujebi-2026-sw-design-ch03-26",sourceQuestionNo:26,sourcePage:"1-45",questionType:"single_choice",questionText:"효과적인 모듈 설계를 위한 유의사항으로 거리가 먼 것은?",choices:["모듈 간의 결합도를 약하게 하면 모듈 독립성이 향상된다.","복잡도와 중복성을 줄이고 일관성을 유지시킨다.","모듈의 기능은 예측이 가능해야 하며 지나치게 제한적이어야 한다.","유지보수가 용이해야 한다."],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"효과적인 모듈은 기능을 예측할 수 있어야 하지만 지나치게 제한적이어서는 안 된다. 낮은 결합도, 낮은 복잡도와 중복성, 높은 유지보수성은 바람직하다.",finalKey:"모듈 기능 = 예측 가능, 지나치게 제한적이면 안 됨",sourceImageUrl:"https://drive.google.com/file/d/12dtESEvFhVCsPiklKcOH5Lv2QHcR14nM/view"},
  {id:"sujebi-2026-sw-design-ch03-27",sourceQuestionNo:27,sourcePage:"1-46",questionType:"single_choice",questionText:"모듈의 독립성을 높이기 위한 결합도(Coupling)와 관련한 설명으로 틀린 것은?",choices:["오류가 발생했을 때 전파되어 다른 오류의 원인이 되는 파문 효과(Ripple Effect)를 최소화해야 한다.","인터페이스가 정확히 설정되어 있지 않을 경우 불필요한 인터페이스가 나타나 모듈 사이의 의존도는 높아지고 결합도가 증가한다.","모듈들이 변수를 공유하여 사용하게 하거나 제어 정보를 교류하게 함으로써 결합도를 낮추어야 한다.","다른 모듈과 데이터 교류가 필요한 경우 전역변수(Global Variable)보다는 매개변수(Parameter)를 사용하는 것이 결합도를 낮추는 데 도움이 된다."],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"변수를 공유하거나 제어 정보를 교환하면 모듈 사이의 결합도가 높아져 독립성이 낮아진다. 독립성을 높이려면 결합도를 낮춰야 한다.",finalKey:"공유 변수·제어정보 교환 → 결합도↑",sourceImageUrl:"https://drive.google.com/file/d/1CirLXs_UH7tvUtHgO5eNXjftWn8SyiUQ/view"},
  {id:"sujebi-2026-sw-design-ch03-28",sourceQuestionNo:28,sourcePage:"1-46",questionType:"single_choice",questionText:"모듈화(Modularity)와 관련한 설명으로 틀린 것은?",choices:["소프트웨어의 모듈은 프로그래밍 언어에서 Subroutine, Function 등으로 표현될 수 있다.","모듈의 수가 증가하면 상대적으로 각 모듈의 크기가 커지며, 모듈 사이의 상호 교류가 감소하여 과부하(Overload) 현상이 나타난다.","모듈화는 시스템을 지능적으로 관리할 수 있도록 해주며, 복잡도 문제를 해결하는 데 도움을 준다.","모듈화는 시스템의 유지보수와 수정을 용이하게 한다."],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"모듈 수가 증가하면 일반적으로 각 모듈의 크기는 작아지고 모듈 간 인터페이스와 상호교류가 증가해 오버헤드가 커질 수 있다.",finalKey:"모듈 수↑ → 각 모듈 크기↓, 인터페이스/오버헤드↑",sourceImageUrl:"https://drive.google.com/file/d/1CirLXs_UH7tvUtHgO5eNXjftWn8SyiUQ/view"},
  {id:"sujebi-2026-sw-design-ch03-29",sourceQuestionNo:29,sourcePage:"1-46",questionType:"single_choice",questionText:"다음 중 가장 결합도가 강한 것은?",choices:["Data Coupling","Stamp Coupling","Common Coupling","Control Coupling"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"결합도는 내용 > 공통 > 외부 > 제어 > 스탬프 > 자료 순으로 강하다. 보기 중에서는 Common Coupling이 가장 강하다.",finalKey:"결합도 강→약: 내용 > 공통 > 외부 > 제어 > 스탬프 > 자료",sourceImageUrl:"https://drive.google.com/file/d/1CirLXs_UH7tvUtHgO5eNXjftWn8SyiUQ/view"},
  {id:"sujebi-2026-sw-design-ch03-30",sourceQuestionNo:30,sourcePage:"1-47",questionType:"single_choice",questionText:"어떤 모듈이 다른 모듈의 내부 논리 조직을 제어하기 위한 목적으로 제어 신호를 이용하여 통신하는 경우이며, 하위 모듈에서 상위 모듈로 제어 신호가 이동하여 상위 모듈에게 처리 명령을 부여하는 권리 전도 현상이 발생하게 되는 결합도는?",choices:["Data Coupling","Stamp Coupling","Control Coupling","Common Coupling"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"제어 결합도는 한 모듈이 다른 모듈의 처리 흐름이나 내부 논리를 제어하기 위한 제어 신호를 전달하는 경우의 결합도다.",finalKey:"제어 신호로 다른 모듈 처리 통제 = Control Coupling",sourceImageUrl:"https://drive.google.com/file/d/1ugJvTUm_soD0UWpH8wXR6jqBHGsGAxU8/view"},
  {id:"sujebi-2026-sw-design-ch03-31",sourceQuestionNo:31,sourcePage:"1-47",questionType:"single_choice",questionText:"시스템에서 모듈 사이의 결합도(Coupling)에 대한 설명으로 옳은 것은?",choices:["한 모듈 내에 있는 처리 요소들 사이의 기능적인 연관 정도를 나타낸다.","결합도가 높으면 시스템 구현 및 유지보수 작업이 쉽다.","모듈 간의 결합도를 약하게 하면 모듈 독립성이 향상된다.","자료 결합도는 내용 결합도보다 결합도가 높다."],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"결합도는 모듈 간 상호의존 정도이며 낮을수록 독립성과 유지보수성이 좋아진다. 모듈 내부 관련 정도는 응집도다.",finalKey:"결합도↓ → 모듈 독립성↑",sourceImageUrl:"https://drive.google.com/file/d/1ugJvTUm_soD0UWpH8wXR6jqBHGsGAxU8/view"},
  {id:"sujebi-2026-sw-design-ch03-32",sourceQuestionNo:32,sourcePage:"1-47",questionType:"single_choice",questionText:"결합도(Coupling)에 대한 설명으로 틀린 것은?",choices:["데이터 결합도(Data Coupling)는 두 모듈이 매개 변수로 자료를 전달할 때, 자료구조 형태로 전달되어 이용될 때 데이터가 결합되어 있다고 한다.","내용 결합도(Content Coupling)는 하나의 모듈이 직접적으로 다른 모듈의 내용을 참조할 때 두 모듈은 내용적으로 결합되어 있다고 한다.","공통 결합도(Common Coupling)는 두 모듈이 동일한 전역 데이터를 접근한다면 공통 결합되어 있다고 한다.","결합도(Coupling)는 두 모듈 간의 상호 작용 또는 의존도 정도를 나타내는 것이다."],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"자료구조 전체를 매개변수로 전달하는 것은 스탬프 결합도다. 데이터 결합도는 필요한 단순 데이터 항목만 매개변수로 전달하는 형태다.",finalKey:"자료구조 전달 = Stamp / 단순 데이터 전달 = Data",sourceImageUrl:"https://drive.google.com/file/d/1ugJvTUm_soD0UWpH8wXR6jqBHGsGAxU8/view"},
  {id:"sujebi-2026-sw-design-ch03-33",sourceQuestionNo:33,sourcePage:"1-48",questionType:"single_choice",questionText:"결합도가 낮은 것부터 높은 것 순으로 옳게 나열한 것은? (ㄱ 내용 결합도, ㄴ 자료 결합도, ㄷ 공통 결합도, ㄹ 스탬프 결합도, ㅁ 외부 결합도, ㅂ 제어 결합도)",choices:["ㄱ → ㄴ → ㄹ → ㅂ → ㅁ → ㄷ","ㄴ → ㄹ → ㅁ → ㅂ → ㄷ → ㄱ","ㄴ → ㄹ → ㅂ → ㅁ → ㄷ → ㄱ","ㄱ → ㄴ → ㄹ → ㅁ → ㅂ → ㄷ"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"결합도가 낮은 순서는 자료 → 스탬프 → 제어 → 외부 → 공통 → 내용이다.",finalKey:"결합도 약→강: 자료 → 스탬프 → 제어 → 외부 → 공통 → 내용",sourceImageUrl:"https://drive.google.com/file/d/11TiIx4Ruu8NGcAceZU4HYZscRPOFhBgu/view"},
  {id:"sujebi-2026-sw-design-ch03-34",sourceQuestionNo:34,sourcePage:"1-48",questionType:"single_choice",questionText:"다음 중 가장 약한 결합도(Coupling)는?",choices:["Common Coupling","Content Coupling","External Coupling","Stamp Coupling"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"보기 중 결합도가 가장 약한 것은 Stamp Coupling이다. 전체 순서는 내용 > 공통 > 외부 > 제어 > 스탬프 > 자료다.",finalKey:"보기 중 최약 결합도 = Stamp",sourceImageUrl:"https://drive.google.com/file/d/11TiIx4Ruu8NGcAceZU4HYZscRPOFhBgu/view"},
  {id:"sujebi-2026-sw-design-ch03-35",sourceQuestionNo:35,sourcePage:"1-48",questionType:"single_choice",questionText:"모듈이 다수의 관련 기능을 가질 때 모듈 안의 구성 요소들이 그 기능을 순차적으로 수행할 경우의 응집도 유형은?",choices:["기능적 응집도","우연적 응집도","논리적 응집도","절차적 응집도"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"절차적 응집도는 모듈 안의 구성요소들이 관련 기능을 일정한 절차·순서에 따라 수행할 때의 응집도다.",finalKey:"관련 기능을 순차 수행 = 절차적 응집도",sourceImageUrl:"https://drive.google.com/file/d/11TiIx4Ruu8NGcAceZU4HYZscRPOFhBgu/view"}
];

const currentIdBeforeCh03_23_35 = state.currentRoundIds?.[state.currentIndex];
const knownCh03_23_35 = new Set(QUESTIONS.map(q => q.id));
const addCh03_23_35 = CH03_QUESTIONS_23_35.filter(q => !knownCh03_23_35.has(q.id));
if (addCh03_23_35.length) QUESTIONS.push(...addCh03_23_35);
const orderedCh03_23 = QUESTIONS.filter(q => q.id.startsWith("sujebi-2026-sw-design-ch03-")).sort((a,b) => a.sourceQuestionNo - b.sourceQuestionNo);
const orderedNonCh03_23 = QUESTIONS.filter(q => !q.id.startsWith("sujebi-2026-sw-design-ch03-"));
QUESTIONS.splice(0, QUESTIONS.length, ...orderedCh03_23, ...orderedNonCh03_23);
if (state.mode !== "weak") {
  state.currentRoundIds = QUESTIONS.map(q => q.id);
  const preserved = state.currentRoundIds.indexOf(currentIdBeforeCh03_23_35);
  state.currentIndex = preserved >= 0 ? preserved : Math.min(state.currentIndex || 0, state.currentRoundIds.length - 1);
  saveState();
}
if (typeof renderDashboardV01 === "function") renderDashboardV01();