const CH01_QUESTIONS_33_48 = [
  {id:"sujebi-2026-sw-design-ch01-33",sourceQuestionNo:33,sourcePage:"1-25",questionType:"single_choice",questionText:"DFD(Data Flow Diagram)에 대한 설명으로 틀린 것은?",choices:["자료 흐름 그래프 또는 버블(Bubble) 차트라고도 한다.","구조적 분석 기법에 이용된다.","시간 흐름을 명확하게 표현할 수 있다.","DFD의 요소는 화살표, 원, 사각형, 직선(단선·이중선)으로 표시한다."],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"DFD는 데이터의 흐름과 처리 관계를 표현하지만 시간의 흐름이나 처리 순서를 명확하게 표현하는 도구는 아니다.",finalKey:"DFD = 자료 흐름, 시간 흐름 표현 아님",sourceImageUrl:"https://drive.google.com/file/d/1XXPGs336s2XSTXwHgWO-cNGf8zpeUrwq/view"},
  {id:"sujebi-2026-sw-design-ch01-34",sourceQuestionNo:34,sourcePage:"1-25",questionType:"single_choice",questionText:"소프트웨어 개발 단계에서 요구분석 과정에 대한 설명으로 거리가 먼 것은?",choices:["분석 결과의 문서화를 통해 향후 유지보수에 유용하게 활용할 수 있다.","개발 비용이 가장 많이 소요되는 단계이다.","자료 흐름도, 자료 사전 등이 효과적으로 이용될 수 있다.","보다 구체적인 명세를 위해 소단위 명세서(Mini-Spec)가 활용될 수 있다."],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"소프트웨어 생명주기에서 일반적으로 유지보수 단계의 비용 비중이 가장 크다. 요구분석은 개발 비용이 가장 많이 드는 단계라고 볼 수 없다.",finalKey:"비용 최다 = 보통 유지보수, 요구분석 아님",sourceImageUrl:"https://drive.google.com/file/d/1XXPGs336s2XSTXwHgWO-cNGf8zpeUrwq/view"},
  {id:"sujebi-2026-sw-design-ch01-35",sourceQuestionNo:35,sourcePage:"1-25",questionType:"single_choice",questionText:"요구사항 분석이 어려운 이유가 아닌 것은?",choices:["개발자와 사용자 간의 지식이나 표현의 차이가 커서 상호 이해가 쉽지 않다.","사용자의 요구는 예외가 거의 없어 열거와 구조화가 어렵지 않다.","사용자의 요구사항이 모호하고 불명확하다.","소프트웨어 개발 과정 중에 요구사항이 계속 변할 수 있다."],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"사용자 요구에는 다양한 예외와 변경이 존재하므로 열거와 구조화가 어렵다. '예외가 거의 없어 어렵지 않다'는 요구분석이 어려운 이유가 아니다.",finalKey:"요구는 예외·변경 많음 → 분석 어려움",sourceImageUrl:"https://drive.google.com/file/d/1XXPGs336s2XSTXwHgWO-cNGf8zpeUrwq/view"},
  {id:"sujebi-2026-sw-design-ch01-36",sourceQuestionNo:36,sourcePage:"1-25",questionType:"single_choice",questionText:"요구분석(Requirement Analysis)에 대한 설명으로 틀린 것은?",choices:["요구분석은 소프트웨어 개발의 실질적인 첫 단계로 사용자의 요구에 대해 이해하는 단계라 할 수 있다.","요구추출(Requirement Elicitation)은 프로젝트 계획 단계에 정의한 문제의 범위 안에 있는 사용자의 요구를 찾는 단계이다.","도메인 분석(Domain Analysis)은 요구에 대한 정보를 수집하고 배경을 분석하여 이를 토대로 모델링을 하게 된다.","기능적(Functional) 요구에서 시스템 구축에 대한 성능, 보안, 품질, 안정 등에 대한 요구사항을 도출한다."],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"성능, 보안, 품질, 안정성 등은 비기능적 요구사항이다. 기능적 요구사항은 시스템이 수행할 기능과 관련된다.",finalKey:"성능·보안·품질·안정 = 비기능 요구",sourceImageUrl:"https://drive.google.com/file/d/1XXPGs336s2XSTXwHgWO-cNGf8zpeUrwq/view"},
  {id:"sujebi-2026-sw-design-ch01-37",sourceQuestionNo:37,sourcePage:"1-25",questionType:"single_choice",questionText:"소프트웨어 설계에서 요구사항 분석에 대한 설명으로 틀린 것은?",choices:["소프트웨어가 무엇을 해야 하는가를 추적하여 요구사항 명세를 작성하는 작업이다.","사용자의 요구를 추출하여 목표를 정하고 어떤 방식으로 해결할 것인지 결정하는 단계이다.","소프트웨어 시스템이 사용되는 동안 발견되는 오류를 정리하는 단계이다.","소프트웨어 개발의 출발점이면서 실질적인 첫 번째 단계이다."],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"시스템 사용 중 발견되는 오류를 찾고 정리하는 것은 테스트·유지보수와 관련된 활동이지 요구사항 분석의 설명이 아니다.",finalKey:"사용 중 오류 정리 ≠ 요구사항 분석",sourceImageUrl:"https://drive.google.com/file/d/1XXPGs336s2XSTXwHgWO-cNGf8zpeUrwq/view"},
  {id:"sujebi-2026-sw-design-ch01-38",sourceQuestionNo:38,sourcePage:"1-26",questionType:"single_choice",questionText:"객체 지향 시스템을 개발할 때 산출물을 명세화, 시각화, 문서화하는 데 사용되며 시스템을 이해하기 쉬운 형태로 표현하여 분석가·의뢰인·설계자의 의사소통을 돕는 표준화된 모델링 언어는?",choices:["JAVA","C","UML","Python"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"UML(Unified Modeling Language)은 객체 지향 시스템의 산출물을 명세·시각화·문서화하기 위한 표준화된 범용 모델링 언어다.",finalKey:"객체지향 표준 모델링 언어 = UML",sourceImageUrl:"https://drive.google.com/file/d/1_FMt-6yiwlUHDQDZwyRROX7mJkSZeYpd/view"},
  {id:"sujebi-2026-sw-design-ch01-39",sourceQuestionNo:39,sourcePage:"1-26",questionType:"single_choice",questionText:"애자일(Agile) 기법 중 스크럼(Scrum)과 관련된 용어에 대한 설명이 틀린 것은?",choices:["스크럼 마스터(Scrum Master)는 스크럼 프로세스를 따르고 팀이 스크럼을 효과적으로 활용할 수 있도록 보장하는 역할 등을 맡는다.","제품 백로그(Product Backlog)는 스크럼 팀이 해결해야 하는 목록으로 소프트웨어 요구사항, 아키텍처 정의 등이 포함될 수 있다.","스프린트(Sprint)는 하나의 완성된 최종 결과물을 만들기 위한 주기로 3달 이상의 장기간으로 결정된다.","속도(Velocity)는 한 번의 스프린트에서 한 팀이 어느 정도의 제품 백로그를 감당할 수 있는지에 대한 추정치로 볼 수 있다."],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"스크럼의 스프린트는 보통 2~4주의 짧은 기간으로 반복 수행한다. 3개월 이상의 장기간으로 정한다는 설명은 틀리다.",finalKey:"Sprint = 보통 2~4주",sourceImageUrl:"https://drive.google.com/file/d/1_FMt-6yiwlUHDQDZwyRROX7mJkSZeYpd/view"},
  {id:"sujebi-2026-sw-design-ch01-40",sourceQuestionNo:40,sourcePage:"1-26",questionType:"single_choice",questionText:"유스케이스(Use Case)의 구성요소 간의 관계에 포함되지 않는 것은?",choices:["연관","확장","구체화","일반화"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"유스케이스 구성요소 간에는 연관, 포함, 확장, 일반화 등의 관계를 사용한다. 구체화는 해당 관계 목록에 포함되지 않는다.",finalKey:"Use Case 관계 ≠ 구체화",sourceImageUrl:"https://drive.google.com/file/d/1_FMt-6yiwlUHDQDZwyRROX7mJkSZeYpd/view"},
  {id:"sujebi-2026-sw-design-ch01-41",sourceQuestionNo:41,sourcePage:"1-26",questionType:"single_choice",questionText:"유스케이스 다이어그램(Use Case Diagram)에 관련된 내용으로 틀린 것은?",choices:["시스템과 상호 작용하는 외부 시스템은 액터로 파악해서는 안 된다.","유스케이스는 사용자 측면에서의 요구사항으로, 사용자가 원하는 목표를 달성하기 위해 수행할 내용을 기술한다.","시스템 액터는 다른 프로젝트에서 이미 개발되어 사용되고 있으며 본 시스템과 데이터를 주고받는 등 서로 연동되는 시스템을 말한다.","액터가 인식할 수 없는 시스템 내부의 기능을 하나의 유스케이스로 파악해서는 안 된다."],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"액터는 사람뿐 아니라 시스템 외부에서 대상 시스템과 상호작용하는 다른 시스템도 포함할 수 있다.",finalKey:"외부 연동 시스템도 Actor 가능",sourceImageUrl:"https://drive.google.com/file/d/1_FMt-6yiwlUHDQDZwyRROX7mJkSZeYpd/view"},
  {id:"sujebi-2026-sw-design-ch01-42",sourceQuestionNo:42,sourcePage:"1-27",questionType:"single_choice",questionText:"객체 지향 개념을 활용한 소프트웨어 구현과 관련한 설명 중 틀린 것은?",choices:["객체(Object)란 필요한 자료 구조와 수행되는 함수들을 가진 하나의 독립된 존재이다.","JAVA에서 정보은닉(Information Hiding)을 표기할 때 private의 의미는 '공개'이다.","상속(Inheritance)은 개별 클래스들을 상속 관계로 묶음으로써 클래스 간의 체계화된 전체 구조를 파악하기 쉽다는 장점이 있다.","같은 클래스에 속하는 개개의 객체이자 하나의 클래스에서 생성된 객체를 인스턴스(Instance)라고 한다."],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"Java의 private 접근제어자는 해당 클래스 내부에서만 접근할 수 있도록 제한하는 것으로 '공개'를 의미하지 않는다.",finalKey:"private = 클래스 내부 접근, 공개 아님",sourceImageUrl:"https://drive.google.com/file/d/1dLuFSEMobG12uJ239WtAf1rcZuh8YqAq/view"},
  {id:"sujebi-2026-sw-design-ch01-43",sourceQuestionNo:43,sourcePage:"1-27",questionType:"single_choice",questionText:"UML 다이어그램 중 순차 다이어그램에 대한 설명으로 틀린 것은?",choices:["객체 간의 동적 상호 작용을 시간 개념을 중심으로 모델링하는 것이다.","주로 시스템의 정적 측면을 모델링하기 위해 사용된다.","일반적으로 다이어그램의 수직 방향이 시간의 흐름을 나타낸다.","회귀 메시지(Self-Message), 제어블록(Statement Block) 등으로 구성된다."],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"순차 다이어그램은 객체 간 동적 상호작용과 메시지 흐름을 시간 순서로 나타내는 행위적 다이어그램이다.",finalKey:"Sequence = 동적 상호작용·시간 순서",sourceImageUrl:"https://drive.google.com/file/d/1dLuFSEMobG12uJ239WtAf1rcZuh8YqAq/view"},
  {id:"sujebi-2026-sw-design-ch01-44",sourceQuestionNo:44,sourcePage:"1-27",questionType:"single_choice",questionText:"소프트웨어를 보다 쉽게 이해할 수 있고 적은 비용으로 수정할 수 있도록 겉으로 보이는 동작의 변화 없이 내부구조를 변경하는 것은?",choices:["Refactoring","Architecting","Specification","Renewal"],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"리팩토링은 외부에서 관찰되는 기능을 바꾸지 않고 코드의 내부 구조를 개선하는 작업이다.",finalKey:"외부 동작 변화 없이 내부 구조 개선 = Refactoring",sourceImageUrl:"https://drive.google.com/file/d/1dLuFSEMobG12uJ239WtAf1rcZuh8YqAq/view"},
  {id:"sujebi-2026-sw-design-ch01-45",sourceQuestionNo:45,sourcePage:"1-27",questionType:"single_choice",questionText:"애자일(Agile) 프로세스 모델에 대한 설명으로 틀린 것은?",choices:["변화에 대한 대응보다는 자세한 계획을 중심으로 소프트웨어를 개발한다.","프로세스와 도구 중심이 아닌 개개인과의 상호 소통을 통해 의견을 수렴한다.","협상과 계약보다는 고객과의 협력을 중시한다.","문서 중심이 아닌 실행 가능한 소프트웨어를 중시한다."],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"애자일은 상세한 장기 계획보다 요구 변화에 유연하고 신속하게 대응하는 것을 중시한다.",finalKey:"Agile = 계획보다 변화 대응",sourceImageUrl:"https://drive.google.com/file/d/1dLuFSEMobG12uJ239WtAf1rcZuh8YqAq/view"},
  {id:"sujebi-2026-sw-design-ch01-46",sourceQuestionNo:46,sourcePage:"1-28",questionType:"single_choice",questionText:"익스트림 프로그래밍에 대한 설명으로 틀린 것은?",choices:["대표적인 구조적 방법론 중 하나이다.","소규모 개발 조직이 불확실하고 변경이 많은 요구를 접하였을 때 적절한 방법이다.","익스트림 프로그래밍을 구동시키는 원리는 상식적인 원리와 경험을 최대한 끌어올리는 것이다.","구체적인 실천 방법을 정의하고 있으며 개발 문서보다는 소스 코드에 중점을 둔다."],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"XP(Extreme Programming)는 대표적인 애자일 방법론이다. 구조적 방법론이라는 설명은 틀리다.",finalKey:"XP = 애자일 방법론",sourceImageUrl:"https://drive.google.com/file/d/1Cgn5VNwMDyICBjCzi3qszWt988C9DIKn/view"},
  {id:"sujebi-2026-sw-design-ch01-47",sourceQuestionNo:47,sourcePage:"1-28",questionType:"single_choice",questionText:"UML에서 사물(Things)로 사용할 수 없는 것은?",choices:["Behavioral Things","Structural Things","Grouping Things","Internet Of Things"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"UML 사물의 유형에는 구조 사물, 행동 사물, 그룹 사물, 주해 사물이 있다. Internet Of Things는 UML 사물 유형이 아니다.",finalKey:"UML Things = 구조·행동·그룹·주해",sourceImageUrl:"https://drive.google.com/file/d/1Cgn5VNwMDyICBjCzi3qszWt988C9DIKn/view"},
  {id:"sujebi-2026-sw-design-ch01-48",sourceQuestionNo:48,sourcePage:"1-28",questionType:"single_choice",questionText:"스크럼에서 해당 스프린트가 계획된 대로 나아가고 있는지, 정해진 목표 달성을 위해 팀 차원의 조정이 필요한지 알 수 있게 하고 수행할 작업의 진행 상황을 확인할 수 있는 것은?",choices:["User Story","Burn Down Chart","Kanban Board","Crystal Chart"],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"Burn Down Chart는 스프린트의 남은 작업량을 시각화하여 목표 대비 진행 상황과 조정 필요성을 확인하게 한다.",finalKey:"Sprint 진행·남은 작업 시각화 = Burn Down Chart",sourceImageUrl:"https://drive.google.com/file/d/1Cgn5VNwMDyICBjCzi3qszWt988C9DIKn/view"}
];

const currentIdBeforeCh01_33_48 = state.currentRoundIds?.[state.currentIndex];
const knownCh01_33_48 = new Set(QUESTIONS.map(q => q.id));
const addCh01_33_48 = CH01_QUESTIONS_33_48.filter(q => !knownCh01_33_48.has(q.id));
if (addCh01_33_48.length) QUESTIONS.push(...addCh01_33_48);
const orderedCh01_33 = QUESTIONS.filter(q => q.id.startsWith("sujebi-2026-sw-design-ch01-")).sort((a,b) => a.sourceQuestionNo - b.sourceQuestionNo);
const orderedNonCh01_33 = QUESTIONS.filter(q => !q.id.startsWith("sujebi-2026-sw-design-ch01-"));
QUESTIONS.splice(0, QUESTIONS.length, ...orderedCh01_33, ...orderedNonCh01_33);
if (state.mode !== "weak") {
  state.currentRoundIds = QUESTIONS.map(q => q.id);
  const preserved = state.currentRoundIds.indexOf(currentIdBeforeCh01_33_48);
  state.currentIndex = preserved >= 0 ? preserved : Math.min(state.currentIndex || 0, state.currentRoundIds.length - 1);
  saveState();
}
if (typeof renderDashboardV01 === "function") renderDashboardV01();