const CH03_QUESTIONS_52_68 = [
  {id:"sujebi-2026-sw-design-ch03-52",sourceQuestionNo:52,sourcePage:"1-53",questionType:"single_choice",questionText:"객체 지향 기법에서 클래스에 속한 각각의 객체를 의미하는 것은?",choices:["인스턴스(Instance)","메시지(Message)","메서드(Method)","모듈(Module)"],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"클래스를 통해 만들어진 실제 실행 객체를 인스턴스라고 한다.",finalKey:"클래스에 속한 실제 객체 = Instance",sourceImageUrl:"https://drive.google.com/file/d/17FC4Klbiy94c9EbUdLnRKBDaQwAEwRhI/view"},
  {id:"sujebi-2026-sw-design-ch03-53",sourceQuestionNo:53,sourcePage:"1-53",questionType:"single_choice",questionText:"객체 지향 기법에서 캡슐화(Encapsulation)에 대한 옳은 내용 모두를 나열한 것은? (ⓐ 캡슐화를 하면 객체 간 결합도가 높아진다. ⓑ 캡슐화된 객체들은 재사용이 용이하다. ⓒ 프로그램 변경에 대한 오류의 파급효과가 적다. ⓓ 인터페이스가 단순해진다.)",choices:["ⓐ, ⓑ","ⓐ, ⓒ, ⓓ","ⓑ, ⓒ, ⓓ","ⓐ, ⓑ, ⓒ, ⓓ"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"캡슐화는 결합도를 낮추고 재사용성을 높이며 변경의 파급효과를 줄이고 인터페이스를 단순화한다.",finalKey:"캡슐화 = 결합도↓·재사용↑·파급효과↓·인터페이스 단순",sourceImageUrl:"https://drive.google.com/file/d/17FC4Klbiy94c9EbUdLnRKBDaQwAEwRhI/view"},
  {id:"sujebi-2026-sw-design-ch03-54",sourceQuestionNo:54,sourcePage:"1-53",questionType:"single_choice",questionText:"객체 지향 개념 중 하나 이상의 유사한 객체들을 묶어 공통된 특성을 표현한 데이터 추상화를 의미하는 것은?",choices:["메서드(Method)","클래스(Class)","상속성(Inheritance)","메시지(Message)"],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"클래스는 유사한 객체들의 공통 속성과 행위를 추상화하여 정의한다.",finalKey:"유사 객체의 공통 특성 추상화 = Class",sourceImageUrl:"https://drive.google.com/file/d/17FC4Klbiy94c9EbUdLnRKBDaQwAEwRhI/view"},
  {id:"sujebi-2026-sw-design-ch03-55",sourceQuestionNo:55,sourcePage:"1-53",questionType:"single_choice",questionText:"객체 간에 메시지를 주고받을 때 각 객체의 세부 내용을 알 필요가 없으므로 인터페이스가 단순해지고 데이터와 데이터를 처리하는 함수를 하나로 묶는 것을 의미하는 것은?",choices:["추상화(Abstraction)","클래스(Class)","캡슐화(Encapsulation)","통합(Integration)"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"캡슐화는 관련 데이터와 함수를 묶고 내부 세부를 감추어 단순한 인터페이스를 제공한다.",finalKey:"데이터+함수 묶기·내부 은닉 = Encapsulation",sourceImageUrl:"https://drive.google.com/file/d/17FC4Klbiy94c9EbUdLnRKBDaQwAEwRhI/view"},
  {id:"sujebi-2026-sw-design-ch03-56",sourceQuestionNo:56,sourcePage:"1-54",questionType:"single_choice",questionText:"캡슐화(Encapsulation)에 관한 설명 중 옳지 않은 것은?",choices:["데이터와 데이터를 처리하는 함수를 하나로 묶는 것이다.","캡슐화된 객체의 세부 내용이 외부에 은폐되어 변경으로 인한 오류의 파급 효과가 적다.","인터페이스가 단순해지고 객체 간의 결합도가 낮아진다.","캡슐화된 객체들은 재사용이 불가능해진다."],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"캡슐화는 재사용성을 높이는 장점이 있다. 재사용이 불가능해진다는 설명은 틀리다.",finalKey:"캡슐화 → 재사용성 향상",sourceImageUrl:"https://drive.google.com/file/d/13JT1lK17XkNnHWZpp-Zhl2-idTPTLNMs/view"},
  {id:"sujebi-2026-sw-design-ch03-57",sourceQuestionNo:57,sourcePage:"1-54",questionType:"single_choice",questionText:"객체 지향 설계에 있어서 정보 은닉(Information Hiding)의 가장 근본적인 목적은?",choices:["코드를 개선하기 위하여","프로그램의 길이를 짧게 하기 위하여","고려되지 않은 영향(Side-Effect)들을 최소화하기 위하여","인터페이스를 최소화하기 위하여"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"정보 은닉은 다른 모듈의 불필요한 접근을 막아 변경에 따른 예상치 못한 부작용을 최소화한다.",finalKey:"정보 은닉 목적 = Side Effect 최소화",sourceImageUrl:"https://drive.google.com/file/d/13JT1lK17XkNnHWZpp-Zhl2-idTPTLNMs/view"},
  {id:"sujebi-2026-sw-design-ch03-58",sourceQuestionNo:58,sourcePage:"1-54",questionType:"single_choice",questionText:"메시지에 의해 객체가 연산을 수행하게 될 때 하나의 메시지에 대해 각 객체가 가지고 있는 고유한 방법으로 응답할 수 있는 능력을 의미하는 객체 지향 개념은?",choices:["캡슐화(Encapsulation)","추상화(Abstraction)","상속성(Inheritance)","다형성(Polymorphism)"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"다형성은 동일한 메시지에 대해 객체마다 고유한 방식으로 응답할 수 있는 성질이다.",finalKey:"같은 메시지, 객체별 다른 응답 = Polymorphism",sourceImageUrl:"https://drive.google.com/file/d/13JT1lK17XkNnHWZpp-Zhl2-idTPTLNMs/view"},
  {id:"sujebi-2026-sw-design-ch03-59",sourceQuestionNo:59,sourcePage:"1-55",questionType:"single_choice",questionText:"객체 지향 기법에서 상위 클래스의 메서드와 속성을 하위 클래스가 물려받는 것을 의미하는 것은?",choices:["추상화(Abstraction)","다형성(Polymorphism)","캡슐화(Encapsulation)","상속성(Inheritance)"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"상속성은 상위 클래스의 속성과 메서드를 하위 클래스가 재정의 없이 물려받아 사용하는 기법이다.",finalKey:"상위 속성·메서드를 하위가 물려받음 = Inheritance",sourceImageUrl:"https://drive.google.com/file/d/18D8YgOGWTEIssLLL_NUFW_AzERe7q3qT/view"},
  {id:"sujebi-2026-sw-design-ch03-60",sourceQuestionNo:60,sourcePage:"1-55",questionType:"single_choice",questionText:"객체 지향 기법의 캡슐화(Encapsulation)에 대한 설명으로 틀린 것은?",choices:["인터페이스가 단순화된다.","소프트웨어 재사용성이 높아진다.","변경 발생 시 오류의 파급효과가 적다.","상위 클래스의 모든 속성과 연산을 하위 클래스가 물려받는 것을 의미한다."],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"상위 클래스의 속성과 메서드를 하위 클래스가 물려받는 것은 상속성에 대한 설명이다.",finalKey:"상위→하위 물려받기 = 상속, 캡슐화 아님",sourceImageUrl:"https://drive.google.com/file/d/18D8YgOGWTEIssLLL_NUFW_AzERe7q3qT/view"},
  {id:"sujebi-2026-sw-design-ch03-61",sourceQuestionNo:61,sourcePage:"1-55",questionType:"single_choice",questionText:"객체 지향에서 정보 은닉과 가장 밀접한 관계가 있는 것은?",choices:["Encapsulation","Class","Method","Instance"],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"캡슐화는 관련 데이터와 함수를 묶고 내부 구현을 은닉하여 공개 인터페이스만 제공한다.",finalKey:"정보 은닉과 가장 밀접 = Encapsulation",sourceImageUrl:"https://drive.google.com/file/d/18D8YgOGWTEIssLLL_NUFW_AzERe7q3qT/view"},
  {id:"sujebi-2026-sw-design-ch03-62",sourceQuestionNo:62,sourcePage:"1-56",questionType:"single_choice",questionText:"객체 지향 설계에서 정보 은닉(Information Hiding)과 관련한 설명으로 틀린 것은?",choices:["필요하지 않은 정보에 접근하지 못하도록 하여 한 모듈 또는 하부 시스템이 다른 모듈의 구현에 영향을 받지 않게 설계되는 것을 의미한다.","모듈들 사이의 독립성을 유지시키는 데 도움이 된다.","설계에서 은닉되어야 할 기본 정보로는 IP 주소와 같은 물리적 코드, 상세 데이터 구조 등이 있다.","모듈 내부의 자료 구조와 접근 동작들에만 수정을 극한하기 때문에 요구사항 변화에 따른 수정이 불가능하다."],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"정보 은닉은 변경의 영향을 국소화하여 오히려 요구사항 변화에 대한 수정과 유지보수를 쉽게 한다.",finalKey:"정보 은닉 = 변경 영향 국소화, 수정 불가능 아님",sourceImageUrl:"https://drive.google.com/file/d/1yUMlOsfkBsk0zGcGBjvGX2ycLarsQQad/view"},
  {id:"sujebi-2026-sw-design-ch03-63",sourceQuestionNo:63,sourcePage:"1-56",questionType:"single_choice",questionText:"소프트웨어 설계에서 사용되는 대표적인 추상화(Abstraction) 기법이 아닌 것은?",choices:["자료 추상화","제어 추상화","과정 추상화","강도 추상화"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"대표적인 추상화 기법은 과정 추상화, 자료 추상화, 제어 추상화다.",finalKey:"추상화 3종 = 과정·자료·제어",sourceImageUrl:"https://drive.google.com/file/d/1yUMlOsfkBsk0zGcGBjvGX2ycLarsQQad/view"},
  {id:"sujebi-2026-sw-design-ch03-64",sourceQuestionNo:64,sourcePage:"1-56",questionType:"single_choice",questionText:"객체 지향 개념에서 연관된 데이터와 함수를 함께 묶어 외부와 경계를 만들고 필요한 인터페이스만을 밖으로 드러내는 과정은?",choices:["메시지(Message)","캡슐화(Encapsulation)","다형성(Polymorphism)","상속(Inheritance)"],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"캡슐화는 관련 데이터와 함수를 하나로 묶고 외부에 필요한 인터페이스만 공개한다.",finalKey:"데이터+함수 묶고 인터페이스만 공개 = Encapsulation",sourceImageUrl:"https://drive.google.com/file/d/1yUMlOsfkBsk0zGcGBjvGX2ycLarsQQad/view"},
  {id:"sujebi-2026-sw-design-ch03-65",sourceQuestionNo:65,sourcePage:"1-56",questionType:"single_choice",questionText:"객체에게 어떤 행위를 하도록 지시하는 명령은?",choices:["Class","Package","Object","Message"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"메시지는 객체에게 특정 행위를 하도록 요청하거나 지시하는 수단이다.",finalKey:"객체에 행위를 지시 = Message",sourceImageUrl:"https://drive.google.com/file/d/1yUMlOsfkBsk0zGcGBjvGX2ycLarsQQad/view"},
  {id:"sujebi-2026-sw-design-ch03-66",sourceQuestionNo:66,sourcePage:"1-57",questionType:"single_choice",questionText:"객체 지향 설계에서 객체가 가지고 있는 속성과 오퍼레이션의 일부를 감추어서 객체의 외부에서는 접근이 불가능하게 하는 개념은?",choices:["조직화(Organizing)","캡슐화(Encapsulation)","정보 은닉(Information Hiding)","구조화(Structuralization)"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"정보 은닉은 객체 내부의 데이터와 메서드 일부를 감추고 공개 인터페이스를 통해서만 접근하도록 하는 원리다.",finalKey:"외부 접근 불가하도록 내부 감춤 = Information Hiding",sourceImageUrl:"https://drive.google.com/file/d/1w-Sc1ToxK7vE8UXrlvnXs2u6CqX9XVQC/view"},
  {id:"sujebi-2026-sw-design-ch03-67",sourceQuestionNo:67,sourcePage:"1-57",questionType:"single_choice",questionText:"객체 지향의 주요 개념에 대한 설명으로 틀린 것은?",choices:["캡슐화는 상위 클래스에서 속성이나 연산을 전달받아 새로운 형태의 클래스로 확장하여 사용하는 것을 의미한다.","객체는 실세계에 존재하거나 생각할 수 있는 것을 말한다.","클래스는 하나 이상의 유사한 객체들을 묶어 공통된 특성을 표현한 것이다.","다형성은 상속받은 여러 개의 하위 객체들이 다른 형태의 특성을 갖는 객체로 이용될 수 있는 성질이다."],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"상위 클래스의 속성이나 연산을 전달받아 확장하는 것은 상속성에 대한 설명이지 캡슐화가 아니다.",finalKey:"상위 특성 전달받아 확장 = 상속성",sourceImageUrl:"https://drive.google.com/file/d/1w-Sc1ToxK7vE8UXrlvnXs2u6CqX9XVQC/view"},
  {id:"sujebi-2026-sw-design-ch03-68",sourceQuestionNo:68,sourcePage:"1-57",questionType:"single_choice",questionText:"객체 지향 분석 방법론 중 Coad-Yourdon 방법에 해당하는 것은?",choices:["E-R 다이어그램을 사용하여 객체의 행위를 데이터 모델링하는 데 초점을 둔 방법이다.","객체, 동적, 기능 모델로 나누어 수행하는 방법이다.","미시적 개발 프로세스와 거시적 개발 프로세스를 모두 사용하는 방법이다.","Use Case를 강조하여 사용하는 방법이다."],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"Coad와 Yourdon 방법은 E-R 다이어그램을 이용하고 객체 식별, 구조 식별, 주체 정의, 속성 및 관계 정의, 서비스 정의 등의 절차로 객체 지향 분석을 수행한다.",finalKey:"Coad-Yourdon = E-R 기반 객체 분석",sourceImageUrl:"https://drive.google.com/file/d/1w-Sc1ToxK7vE8UXrlvnXs2u6CqX9XVQC/view"}
];

const currentIdBeforeCh03_52_68 = state.currentRoundIds?.[state.currentIndex];
const ch03Known52_68 = new Set(QUESTIONS.map(q => q.id));
const ch03Add52_68 = CH03_QUESTIONS_52_68.filter(q => !ch03Known52_68.has(q.id));
if (ch03Add52_68.length) QUESTIONS.push(...ch03Add52_68);
const orderedCh03_52 = QUESTIONS.filter(q => q.id.startsWith("sujebi-2026-sw-design-ch03-")).sort((a,b) => a.sourceQuestionNo - b.sourceQuestionNo);
const orderedNonCh03_52 = QUESTIONS.filter(q => !q.id.startsWith("sujebi-2026-sw-design-ch03-"));
QUESTIONS.splice(0, QUESTIONS.length, ...orderedCh03_52, ...orderedNonCh03_52);
if (state.mode !== "weak") {
  state.currentRoundIds = QUESTIONS.map(q => q.id);
  const preserved = state.currentRoundIds.indexOf(currentIdBeforeCh03_52_68);
  state.currentIndex = preserved >= 0 ? preserved : Math.min(state.currentIndex || 0, state.currentRoundIds.length - 1);
  saveState();
}
if (typeof renderDashboardV01 === "function") renderDashboardV01();
