const CH04_QUESTIONS_1_12 = [
  {id:"sujebi-2026-sw-design-ch04-01",sourceQuestionNo:1,sourcePage:"1-70",questionType:"single_choice",questionText:"검토회의 전에 요구사항 명세서를 미리 배포하여 사전 검토한 후 짧은 검토 회의를 통해 오류를 조기에 검출하는 데 목적을 두는 요구사항 검토 방법은?",choices:["빌드 검증","동료 검토","워크 스루","개발자 검토"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"워크 스루는 검토 자료를 회의 전에 배포하여 사전 검토한 뒤 짧은 회의를 통해 오류를 조기에 검출하고 문서화하는 비공식적 검토 방법이다.",finalKey:"사전 배포 + 짧은 검토회의 = Walkthrough",sourceImageUrl:"https://drive.google.com/file/d/1HmgUgJs8WNDaJgiWYQCOoFd_TjbEqCDP/view"},
  {id:"sujebi-2026-sw-design-ch04-02",sourceQuestionNo:2,sourcePage:"1-70",questionType:"single_choice",questionText:"인터페이스 요구사항 검토 방법에 대한 설명이 옳은 것은?",choices:["리팩토링: 작성자 이외의 전문가 검토 그룹이 요구사항 명세서를 상세히 조사하여 결함·표준 위배·문제점을 파악한다.","동료 검토: 요구사항 명세서 작성자가 내용을 설명하고 이해관계자들이 설명을 들으면서 결함을 발견한다.","일반화 관계: 자동화된 요구사항 관리 도구를 이용하여 요구사항 추적성과 일반성을 검토한다.","CASE 도구: 검토 자료를 회의 전에 배포하여 사전 검토한 후 짧은 검토 회의로 결함을 발견한다."],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"동료 검토(Peer Review)는 보통 2~3명이 참여하며 요구사항 명세서 작성자가 내용을 설명하고 이해관계자들이 설명을 들으면서 결함을 발견하는 형태로 진행한다.",finalKey:"작성자가 설명 + 이해관계자가 결함 발견 = Peer Review",sourceImageUrl:"https://drive.google.com/file/d/1HmgUgJs8WNDaJgiWYQCOoFd_TjbEqCDP/view"},
  {id:"sujebi-2026-sw-design-ch04-03",sourceQuestionNo:3,sourcePage:"1-71",questionType:"single_choice",questionText:"정형 기술 검토(FTR)의 지침 사항으로 가장 옳지 않은 것은?",choices:["제품의 검토에만 집중한다.","문제 영역을 명확히 표현한다.","참가자의 수를 제한하고 사전 준비를 강요한다.","논쟁이나 반박을 제한하지 않는다."],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"FTR에서는 검토 목적을 유지하기 위해 논쟁과 반박을 제한해야 한다. 제품 검토 집중, 문제 영역 명확화, 참가자 수 제한과 사전 준비는 지침에 해당한다.",finalKey:"FTR = 논쟁·반박 제한",sourceImageUrl:"https://drive.google.com/file/d/1ippNK9X4C4FqdUkGt-8ASZLqADN_xzky/view"},
  {id:"sujebi-2026-sw-design-ch04-04",sourceQuestionNo:4,sourcePage:"1-71",questionType:"single_choice",questionText:"요구사항 명세기법에 대한 설명으로 틀린 것은?",choices:["비정형 명세기법은 사용자의 요구를 표현할 때 자연어를 기반으로 서술한다.","비정형 명세기법은 사용자의 요구를 표현할 때 Z 비정형 명세기법을 사용한다.","정형 명세기법은 사용자의 요구를 표현할 때 수학적인 원리와 표기법을 이용한다.","정형 명세기법은 비정형 명세기법에 비해 표현이 간결하다."],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"Z는 수학적 표기법을 사용하는 정형 명세 언어에 해당한다. 비정형 명세는 자연어 중심이다.",finalKey:"Z = 정형 명세기법",sourceImageUrl:"https://drive.google.com/file/d/1ippNK9X4C4FqdUkGt-8ASZLqADN_xzky/view"},
  {id:"sujebi-2026-sw-design-ch04-05",sourceQuestionNo:5,sourcePage:"1-71",questionType:"single_choice",questionText:"요구사항 검증(Requirements Validation)과 관련한 설명으로 틀린 것은?",choices:["요구사항이 고객이 정말 원하는 시스템을 제대로 정의하고 있는지 점검하는 과정이다.","개발 완료 이후 문제 발견 시 재작업 비용이 커질 수 있어 요구사항 검증은 중요하다.","요구사항이 실제 요구를 반영하는지와 문서상의 요구사항이 서로 상충되지 않는지 등을 점검한다.","요구사항 검증 과정을 통해 모든 요구사항 문제를 발견할 수 있다."],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"요구사항 검증은 매우 중요하지만 모든 요구사항 문제를 완전히 발견한다고 보장할 수는 없다.",finalKey:"Validation ≠ 모든 문제 100% 발견",sourceImageUrl:"https://drive.google.com/file/d/1ippNK9X4C4FqdUkGt-8ASZLqADN_xzky/view"},
  {id:"sujebi-2026-sw-design-ch04-06",sourceQuestionNo:6,sourcePage:"1-71",questionType:"single_choice",questionText:"요구사항 개발 프로세스의 순서로 옳은 것은? (ㄱ 도출, ㄴ 분석, ㄷ 명세, ㄹ 확인)",choices:["ㄱ → ㄴ → ㄷ → ㄹ","ㄱ → ㄷ → ㄴ → ㄹ","ㄱ → ㄹ → ㄴ → ㄷ","ㄱ → ㄴ → ㄹ → ㄷ"],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"요구사항 개발 절차는 도출(Elicitation) → 분석(Analysis) → 명세(Specification) → 확인/검증(Validation) 순이다.",finalKey:"도출 → 분석 → 명세 → 확인",sourceImageUrl:"https://drive.google.com/file/d/1ippNK9X4C4FqdUkGt-8ASZLqADN_xzky/view"},
  {id:"sujebi-2026-sw-design-ch04-07",sourceQuestionNo:7,sourcePage:"1-72",questionType:"single_choice",questionText:"소프트웨어 공학에서 워크스루(Walkthrough)에 대한 설명으로 틀린 것은?",choices:["사용사례를 확장하여 명세하거나 설계 다이어그램, 원시 코드, 테스트 케이스 등에 적용할 수 있다.","복잡한 알고리즘 또는 반복, 실시간 동작, 병행 처리와 같은 기능이나 동작을 이해하려고 할 때 유용하다.","인스펙션(Inspection)과 동일한 의미를 가진다.","단순한 테스트 케이스를 이용하여 프로덕트를 수작업으로 수행해 보는 것이다."],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"워크스루는 비공식적 검토이고 인스펙션은 다른 전문가나 팀이 오류를 찾는 공식적 검토 방법이므로 동일한 의미가 아니다.",finalKey:"Walkthrough ≠ Inspection",sourceImageUrl:"https://drive.google.com/file/d/19zDKGWdu_9txMCBn1pUK81Vr2Y1ynRJS/view"},
  {id:"sujebi-2026-sw-design-ch04-08",sourceQuestionNo:8,sourcePage:"1-72",questionType:"single_choice",questionText:"인스펙션 과정은 '계획 → (가) → (나) → (다) → (라) → (마)' 순으로 진행된다. 보기(준비, 사전 교육, 인스펙션 회의, 수정, 후속 조치)와 올바르게 연결된 것은?",choices:["(가)=사전 교육, (나)=인스펙션 회의","(나)=준비, (다)=인스펙션 회의","(다)=인스펙션 회의, (라)=후속 조치","(라)=수정, (마)=사전 교육"],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"인스펙션 절차는 계획 → 사전 교육 → 준비 → 인스펙션 회의 → 수정 → 후속 조치 순이다.",finalKey:"계획 → 사전교육 → 준비 → 회의 → 수정 → 후속조치",sourceImageUrl:"https://drive.google.com/file/d/19zDKGWdu_9txMCBn1pUK81Vr2Y1ynRJS/view"},
  {id:"sujebi-2026-sw-design-ch04-09",sourceQuestionNo:9,sourcePage:"1-72",questionType:"single_choice",questionText:"요구사항 분석에서 비기능적(Nonfunctional) 요구에 대한 설명으로 옳은 것은?",choices:["시스템의 처리량, 반응 시간 등의 성능 요구나 품질 요구는 비기능적 요구에 해당하지 않는다.","차량 대여 시스템이 제공하는 모든 화면이 3초 이내에 사용자에게 보여야 한다는 것은 비기능적 요구이다.","시스템 구축과 관련된 안전·보안 요구사항들은 비기능적 요구에 해당하지 않는다.","금융 시스템은 조회·인출·입금·송금 기능이 있어야 한다는 것은 비기능적 요구이다."],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"응답 시간처럼 성능·품질·제약을 규정하는 요구는 비기능 요구다. 조회·인출·입금·송금 같은 구체 기능은 기능 요구다.",finalKey:"3초 이내 응답 = 성능 = 비기능 요구",sourceImageUrl:"https://drive.google.com/file/d/19zDKGWdu_9txMCBn1pUK81Vr2Y1ynRJS/view"},
  {id:"sujebi-2026-sw-design-ch04-10",sourceQuestionNo:10,sourcePage:"1-73",questionType:"single_choice",questionText:"소프트웨어 개발 방법 중 요구사항 분석(Requirements Analysis)과 거리가 먼 것은?",choices:["비용과 일정에 대한 제약설정","타당성 조사","요구사항 정의 문서화","설계 명세서 작성"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"요구사항 분석은 제약 설정, 타당성 조사, 요구사항 정의 및 문서화 등을 포함한다. 설계 명세서 작성은 이후 설계 단계에 가깝다.",finalKey:"설계 명세서 작성 = 요구분석 단계 아님",sourceImageUrl:"https://drive.google.com/file/d/1Odo0h9_e3QxaMGHG3JAUX281eWxKSH4B/view"},
  {id:"sujebi-2026-sw-design-ch04-11",sourceQuestionNo:11,sourcePage:"1-73",questionType:"single_choice",questionText:"이해관계자와 직접 대화를 통해 정보를 구하는 정보 수집 방법은?",choices:["인터뷰","브레인스토밍","델파이 기법","설문 조사"],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"인터뷰는 이해관계자와 직접 대화하여 정보를 수집하는 공식적·비공식적 정보 수집 방법이다.",finalKey:"직접 대화로 정보 수집 = Interview",sourceImageUrl:"https://drive.google.com/file/d/1Odo0h9_e3QxaMGHG3JAUX281eWxKSH4B/view"},
  {id:"sujebi-2026-sw-design-ch04-12",sourceQuestionNo:12,sourcePage:"1-73",questionType:"single_choice",questionText:"시스템 인터페이스를 구성하는 시스템으로, 연계할 데이터를 데이터베이스와 애플리케이션으로부터 연계 테이블 또는 파일 형태로 생성하여 송신하는 시스템은?",choices:["연계 서버","중계 서버","송신 시스템","수신 시스템"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"송신 시스템은 연계할 데이터를 DB와 애플리케이션에서 추출해 연계 테이블 또는 파일 형태로 생성하여 송신한다.",finalKey:"연계 데이터 생성·송신 = 송신 시스템",sourceImageUrl:"https://drive.google.com/file/d/1Odo0h9_e3QxaMGHG3JAUX281eWxKSH4B/view"}
];

const beforeId = state.currentRoundIds[state.currentIndex];
const known = new Set(QUESTIONS.map(q => q.id));
const ch04Additions = CH04_QUESTIONS_1_12.filter(q => !known.has(q.id));
if (ch04Additions.length) QUESTIONS.push(...ch04Additions);

const ch04 = QUESTIONS.filter(q => q.id.startsWith("sujebi-2026-sw-design-ch04-") || /^sujebi-2026-sw-design-(1[3-9]|2[0-2])$/.test(q.id))
  .sort((a,b) => a.sourceQuestionNo - b.sourceQuestionNo);
const ch05 = QUESTIONS.filter(q => q.id.startsWith("sujebi-2026-sw-design-ch05-")).sort((a,b) => a.sourceQuestionNo - b.sourceQuestionNo);
const other = QUESTIONS.filter(q => !ch04.includes(q) && !ch05.includes(q));
QUESTIONS.splice(0, QUESTIONS.length, ...ch04, ...ch05, ...other);

if (state.mode !== "weak") {
  state.currentRoundIds = QUESTIONS.map(q => q.id);
  const idx = state.currentRoundIds.indexOf(beforeId);
  state.currentIndex = idx >= 0 ? idx : 0;
  saveState();
}

if (typeof renderDashboardV01 === "function") renderDashboardV01();
