const CH01_QUESTIONS_17_32 = [
  {id:"sujebi-2026-sw-design-ch01-17",sourceQuestionNo:17,sourcePage:"1-21",questionType:"single_choice",questionText:"UML(Unified Modeling Language)에 대한 설명 중 틀린 것은?",choices:["기능적 모델은 사용자 측면에서 본 시스템 기능이며 UML에서는 Use Case Diagram을 사용한다.","정적 모델은 객체, 속성, 연관 관계, 오퍼레이션의 시스템 구조를 나타내며 UML에서는 Class Diagram을 사용한다.","동적 모델은 시스템의 내부 동작을 말하며 UML에서는 Sequence Diagram, State Diagram, Activity Diagram을 사용한다.","State Diagram은 객체들 사이의 메시지 교환을 나타내며, Sequence Diagram은 하나의 객체가 가진 상태와 그 상태의 변화에 의한 동작 순서를 나타낸다."],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"Sequence Diagram이 객체 사이의 메시지 교환을 나타내고 State Diagram은 하나의 객체의 상태와 상태 변화에 따른 동작을 나타낸다. 4번은 둘을 반대로 설명했다.",finalKey:"Sequence=메시지 / State=상태 변화",sourceImageUrl:"https://drive.google.com/file/d/1E7fz7tP47lihvNe5txQ22xMnJHEAkARl/view"},
  {id:"sujebi-2026-sw-design-ch01-18",sourceQuestionNo:18,sourcePage:"1-21",questionType:"single_choice",questionText:"다음 중 요구사항 모델링에 활용되지 않는 것은?",choices:["애자일(Agile) 방법","유스케이스 다이어그램(Use Case Diagram)","시퀀스 다이어그램(Sequence Diagram)","단계 다이어그램(Phase Diagram)"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"요구사항 모델링에는 UML의 유스케이스·시퀀스 다이어그램 등을 활용하며 애자일 방식을 적용할 수도 있다. Phase Diagram은 대표적인 요구사항 모델링 도구가 아니다.",finalKey:"요구사항 모델링 ≠ Phase Diagram",sourceImageUrl:"https://drive.google.com/file/d/1E7fz7tP47lihvNe5txQ22xMnJHEAkARl/view"},
  {id:"sujebi-2026-sw-design-ch01-19",sourceQuestionNo:19,sourcePage:"1-21",questionType:"single_choice",questionText:"UML 모델에서 한 사물의 명세가 바뀌면 다른 사물에 영향을 주며, 일반적으로 한 클래스가 다른 클래스를 오퍼레이션의 매개변수로 사용하는 경우에 나타나는 관계는?",choices:["Dependency","Realization","Generalization","Association"],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"의존(Dependency)은 한 사물의 변경이 다른 사물에 영향을 미치는 비교적 짧은 관계이며 다른 클래스를 매개변수 등으로 사용할 때 나타날 수 있다.",finalKey:"한 사물 변경이 다른 사물에 영향 = Dependency",sourceImageUrl:"https://drive.google.com/file/d/1E7fz7tP47lihvNe5txQ22xMnJHEAkARl/view"},
  {id:"sujebi-2026-sw-design-ch01-20",sourceQuestionNo:20,sourcePage:"1-21",questionType:"single_choice",questionText:"클래스 다이어그램의 요소로, 클래스의 동작을 의미하고 클래스에 속하는 객체에 적용될 메서드를 정의하며 UML에서는 동작에 대한 인터페이스를 지칭하는 용어는?",choices:["Instance","Operation","Item","Hiding"],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"Operation은 클래스의 동작을 의미하며 클래스 객체에 적용될 메서드 또는 동작 인터페이스를 정의한다.",finalKey:"클래스의 동작·메서드 정의 = Operation",sourceImageUrl:"https://drive.google.com/file/d/1E7fz7tP47lihvNe5txQ22xMnJHEAkARl/view"},
  {id:"sujebi-2026-sw-design-ch01-21",sourceQuestionNo:21,sourcePage:"1-22",questionType:"single_choice",questionText:"요구사항 정의 및 분석·설계의 결과물을 표현하기 위한 모델링 과정에서 사용되는 다이어그램(Diagram)이 아닌 것은?",choices:["Data Flow Diagram","UML Diagram","E-R Diagram","AVL Diagram"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"요구사항 및 설계 모델링에는 DFD, UML Diagram, E-R Diagram 등이 사용된다. AVL은 균형 이진 탐색 트리이며 AVL Diagram이라는 대표 모델링 다이어그램은 없다.",finalKey:"모델링 다이어그램 ≠ AVL Diagram",sourceImageUrl:"https://drive.google.com/file/d/1foXcIyH3DgkIiSbt8FhEquPPaBnsEhK_/view"},
  {id:"sujebi-2026-sw-design-ch01-22",sourceQuestionNo:22,sourcePage:"1-22",questionType:"single_choice",questionText:"순차 다이어그램(Sequence Diagram)과 관련한 설명으로 틀린 것은?",choices:["객체들의 상호 작용을 나타내기 위해 사용한다.","시간의 흐름에 따라 객체들이 주고받는 메시지의 전달 과정을 강조한다.","동적 다이어그램보다는 정적 다이어그램에 가깝다.","교류 다이어그램(Interaction Diagram)의 한 종류로 볼 수 있다."],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"Sequence Diagram은 객체 사이의 메시지와 시간 흐름을 나타내는 동적·행위적 다이어그램이다.",finalKey:"Sequence = 동적 다이어그램",sourceImageUrl:"https://drive.google.com/file/d/1foXcIyH3DgkIiSbt8FhEquPPaBnsEhK_/view"},
  {id:"sujebi-2026-sw-design-ch01-23",sourceQuestionNo:23,sourcePage:"1-22",questionType:"single_choice",questionText:"XP(eXtreme Programming)의 5가지 가치로 거리가 먼 것은?",choices:["용기","의사소통","정형 분석","피드백"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"XP의 5가지 가치는 용기, 단순성, 의사소통, 피드백, 존중이다. 정형 분석은 XP 가치가 아니다.",finalKey:"XP 5가치 = 용기·단순성·의사소통·피드백·존중",sourceImageUrl:"https://drive.google.com/file/d/1foXcIyH3DgkIiSbt8FhEquPPaBnsEhK_/view"},
  {id:"sujebi-2026-sw-design-ch01-24",sourceQuestionNo:24,sourcePage:"1-22",questionType:"single_choice",questionText:"애자일 기법에 대한 설명으로 맞지 않는 것은?",choices:["절차와 도구보다 개인과 소통을 중요하게 생각한다.","계획에 중점을 두어 변경 대응이 난해하다.","소프트웨어가 잘 실행되는 데 가치를 둔다.","고객과의 피드백을 중요하게 생각한다."],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"애자일은 계획 고수보다 변화에 대한 대응을 중시한다. 상세 계획 때문에 변경 대응이 어렵다는 설명은 애자일의 특성과 반대다.",finalKey:"Agile = 계획보다 변화 대응",sourceImageUrl:"https://drive.google.com/file/d/1foXcIyH3DgkIiSbt8FhEquPPaBnsEhK_/view"},
  {id:"sujebi-2026-sw-design-ch01-25",sourceQuestionNo:25,sourcePage:"1-23",questionType:"single_choice",questionText:"애자일 방법론에 해당하지 않는 것은?",choices:["기능 중심 개발","스크럼","익스트림 프로그래밍","모듈 중심 개발"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"기능 중심 개발(FDD), Scrum, XP는 대표적인 애자일 방법론이다. 모듈 중심 개발은 대표 애자일 방법론 분류가 아니다.",finalKey:"Agile ≠ 모듈 중심 개발",sourceImageUrl:"https://drive.google.com/file/d/1vKmzsTSpBJU6y6PLmDimqgDPsmcXxtT6/view"},
  {id:"sujebi-2026-sw-design-ch01-26",sourceQuestionNo:26,sourcePage:"1-23",questionType:"single_choice",questionText:"UML의 기본 구성요소가 아닌 것은?",choices:["Things","Terminal","Relationship","Diagram"],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"UML의 기본 구성요소는 사물(Things), 관계(Relationship), 다이어그램(Diagram)이다. Terminal은 UML 기본 구성요소가 아니다.",finalKey:"UML 구성 = Things·Relationship·Diagram",sourceImageUrl:"https://drive.google.com/file/d/1vKmzsTSpBJU6y6PLmDimqgDPsmcXxtT6/view"},
  {id:"sujebi-2026-sw-design-ch01-27",sourceQuestionNo:27,sourcePage:"1-23",questionType:"single_choice",questionText:"다음 중 자료 사전(Data Dictionary)에서 선택의 의미를 나타내는 것은?",choices:["[ ]","{ }","+","**"],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"자료사전에서 [ ]는 선택, { }는 반복, +는 연결, **는 설명이나 주석을 의미한다.",finalKey:"DD 선택 = [ ]",sourceImageUrl:"https://drive.google.com/file/d/1vKmzsTSpBJU6y6PLmDimqgDPsmcXxtT6/view"},
  {id:"sujebi-2026-sw-design-ch01-28",sourceQuestionNo:28,sourcePage:"1-23",questionType:"single_choice",questionText:"XP(eXtreme Programming)의 기본원리로 볼 수 없는 것은?",choices:["Linear Sequential Method","Pair Programming","Collective Ownership","Continuous Integration"],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"Pair Programming, Collective Ownership, Continuous Integration은 XP의 주요 실천 원리다. Linear Sequential Method는 폭포수식 선형 순차 모델에 가까우며 XP 원리가 아니다.",finalKey:"XP 원리 ≠ Linear Sequential Method",sourceImageUrl:"https://drive.google.com/file/d/1vKmzsTSpBJU6y6PLmDimqgDPsmcXxtT6/view"},
  {id:"sujebi-2026-sw-design-ch01-29",sourceQuestionNo:29,sourcePage:"1-24",questionType:"single_choice",questionText:"애자일 개발 방법론이 아닌 것은?",choices:["스크럼(Scrum)","익스트림 프로그래밍(XP; eXtreme Programming)","기능 주도 개발(FDD; Feature Driven Development)","하둡(Hadoop)"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"Hadoop은 오픈소스 기반 분산 컴퓨팅·빅데이터 처리 플랫폼으로 애자일 개발 방법론이 아니다.",finalKey:"Hadoop ≠ Agile 방법론",sourceImageUrl:"https://drive.google.com/file/d/10tbVC5jw4ZUTzl5PygxxHOSwniH4y8yD/view"},
  {id:"sujebi-2026-sw-design-ch01-30",sourceQuestionNo:30,sourcePage:"1-24",questionType:"single_choice",questionText:"애자일 개발 방법론과 관련한 설명으로 틀린 것은?",choices:["빠른 릴리즈를 통해 문제점을 빠르게 파악할 수 있다.","정확한 결과 도출을 위해 계획 수립과 문서화에 중점을 둔다.","고객과의 의사소통을 중요하게 생각한다.","진화하는 요구사항을 수용하는 데 적합하다."],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"애자일은 포괄적인 문서와 상세 계획보다 동작하는 소프트웨어, 고객 협력, 변화 대응을 중시한다.",finalKey:"Agile ≠ 계획·문서 중심",sourceImageUrl:"https://drive.google.com/file/d/10tbVC5jw4ZUTzl5PygxxHOSwniH4y8yD/view"},
  {id:"sujebi-2026-sw-design-ch01-31",sourceQuestionNo:31,sourcePage:"1-24",questionType:"single_choice",questionText:"애자일 소프트웨어 개발 기법의 가치가 아닌 것은?",choices:["프로세스와 도구보다는 개인과 상호 작용에 더 가치를 둔다.","계약 협상보다는 고객과의 협업에 더 가치를 둔다.","실제 작동하는 소프트웨어보다는 이해하기 좋은 문서에 더 가치를 둔다.","계획을 따르기보다는 변화에 대응하는 것에 더 가치를 둔다."],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"애자일 선언은 포괄적 문서보다 작동하는 소프트웨어를 더 중시한다.",finalKey:"Agile = 문서보다 작동 SW",sourceImageUrl:"https://drive.google.com/file/d/10tbVC5jw4ZUTzl5PygxxHOSwniH4y8yD/view"},
  {id:"sujebi-2026-sw-design-ch01-32",sourceQuestionNo:32,sourcePage:"1-24",questionType:"single_choice",questionText:"익스트림 프로그래밍(XP)에 대한 설명으로 틀린 것은?",choices:["빠른 개발을 위해 테스트를 수행하지 않는다.","사용자의 요구사항은 언제든지 변할 수 있다.","고객과 직접 대면하며 요구사항을 이야기하기 위해 사용자 스토리(User Story)를 활용할 수 있다.","기존의 방법론에 비해 실용성(Pragmatism)을 강조한 것이라고 볼 수 있다."],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"XP는 테스트 기반 개발(TDD)과 지속적인 테스트를 중시한다. 빠른 개발을 위해 테스트를 하지 않는다는 설명은 틀리다.",finalKey:"XP = 테스트 중시(TDD)",sourceImageUrl:"https://drive.google.com/file/d/10tbVC5jw4ZUTzl5PygxxHOSwniH4y8yD/view"}
];

const currentIdBeforeCh01_17_32 = state.currentRoundIds?.[state.currentIndex];
const knownCh01_17_32 = new Set(QUESTIONS.map(q => q.id));
const addCh01_17_32 = CH01_QUESTIONS_17_32.filter(q => !knownCh01_17_32.has(q.id));
if (addCh01_17_32.length) QUESTIONS.push(...addCh01_17_32);
const orderedCh01_17 = QUESTIONS.filter(q => q.id.startsWith("sujebi-2026-sw-design-ch01-")).sort((a,b) => a.sourceQuestionNo - b.sourceQuestionNo);
const orderedNonCh01_17 = QUESTIONS.filter(q => !q.id.startsWith("sujebi-2026-sw-design-ch01-"));
QUESTIONS.splice(0, QUESTIONS.length, ...orderedCh01_17, ...orderedNonCh01_17);
if (state.mode !== "weak") {
  state.currentRoundIds = QUESTIONS.map(q => q.id);
  const preserved = state.currentRoundIds.indexOf(currentIdBeforeCh01_17_32);
  state.currentIndex = preserved >= 0 ? preserved : Math.min(state.currentIndex || 0, state.currentRoundIds.length - 1);
  saveState();
}
if (typeof renderDashboardV01 === "function") renderDashboardV01();