const CH01_QUESTIONS_01_16 = [
  {id:"sujebi-2026-sw-design-ch01-01",sourceQuestionNo:1,sourcePage:"1-16",questionType:"single_choice",questionText:"소프트웨어 설계 시 구축된 플랫폼의 성능 특성 분석에 사용되는 측정 항목이 아닌 것은?",choices:["응답시간(Response Time)","가용성(Availability)","사용률(Utilization)","서버 튜닝(Server Tuning)"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"플랫폼 성능 특성의 대표 측정 항목에는 경과시간, 사용률, 응답시간, 가용성 등이 있다. 서버 튜닝은 측정 항목이 아니라 성능 개선 활동이다.",finalKey:"플랫폼 성능 측정 ≠ Server Tuning",sourceImageUrl:"https://drive.google.com/file/d/1yDgbwYAW-l5A_l1Lo2KH1nqSomjce801/view"},
  {id:"sujebi-2026-sw-design-ch01-02",sourceQuestionNo:2,sourcePage:"1-16",questionType:"single_choice",questionText:"DBMS 분석 시 고려사항으로 거리가 먼 것은?",choices:["가용성","성능","네트워크 구성도","상호 호환성"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"DBMS 현행 시스템 분석에서는 가용성, 성능, 상호 호환성, 기술 지원, 구축 비용 등을 고려한다. 네트워크 구성도는 네트워크 분석의 직접 대상이다.",finalKey:"DBMS 분석 고려 ≠ 네트워크 구성도",sourceImageUrl:"https://drive.google.com/file/d/1yDgbwYAW-l5A_l1Lo2KH1nqSomjce801/view"},
  {id:"sujebi-2026-sw-design-ch01-03",sourceQuestionNo:3,sourcePage:"1-16",questionType:"single_choice",questionText:"현행 시스템 분석에서 고려하지 않아도 되는 항목은?",choices:["DBMS 분석","네트워크 분석","운영체제 분석","인적 자원 분석"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"현행 시스템 분석에서는 운영체제, 네트워크, DBMS 등 기술 환경을 분석한다. 인적 자원 분석은 이 문맥의 필수 기술 분석 항목이 아니다.",finalKey:"현행 시스템 기술 분석 ≠ 인적 자원",sourceImageUrl:"https://drive.google.com/file/d/1yDgbwYAW-l5A_l1Lo2KH1nqSomjce801/view"},
  {id:"sujebi-2026-sw-design-ch01-04",sourceQuestionNo:4,sourcePage:"1-17",questionType:"single_choice",questionText:"요구사항 분석 시에 필요한 기술로 가장 거리가 먼 것은?",choices:["청취와 인터뷰 질문 기술","분석과 중재 기술","설계 및 코딩 기술","관찰 및 모델 작성 기술"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"요구사항 분석에는 청취·인터뷰, 분석·중재, 관찰, 작성·조직, 모델 작성 등의 기술이 필요하다. 설계 및 코딩은 후속 개발 단계의 기술이다.",finalKey:"요구분석 기술 ≠ 설계·코딩",sourceImageUrl:"https://drive.google.com/file/d/1_yB0zngV5ZX93SzSLr4gdDCbvHmZwGwA/view"},
  {id:"sujebi-2026-sw-design-ch01-05",sourceQuestionNo:5,sourcePage:"1-17",questionType:"single_choice",questionText:"자료 사전에서 자료의 생략을 의미하는 기호는?",choices:["{ }","**","=","( )"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"자료사전에서 ( )는 자료의 생략 가능, { }는 반복, **는 설명·주석, =는 정의를 의미한다.",finalKey:"DD 생략 가능 = ( )",sourceImageUrl:"https://drive.google.com/file/d/1_yB0zngV5ZX93SzSLr4gdDCbvHmZwGwA/view"},
  {id:"sujebi-2026-sw-design-ch01-06",sourceQuestionNo:6,sourcePage:"1-17",questionType:"single_choice",questionText:"자료 사전에서 자료의 반복을 의미하는 것은?",choices:["=","( )","{ }","[ ]"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"자료사전에서 { }는 반복을 의미한다. [ ]는 선택, ( )는 생략 가능, =는 정의다.",finalKey:"DD 반복 = { }",sourceImageUrl:"https://drive.google.com/file/d/1_yB0zngV5ZX93SzSLr4gdDCbvHmZwGwA/view"},
  {id:"sujebi-2026-sw-design-ch01-07",sourceQuestionNo:7,sourcePage:"1-17",questionType:"single_choice",questionText:"데이터 흐름도(DFD)의 구성요소에 포함되지 않는 것은?",choices:["Process","Data Flow","Data Store","Data Dictionary"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"DFD의 구성요소는 Process, Data Flow, Data Store, Terminator이다. Data Dictionary는 DFD를 보완하는 별도 명세 도구다.",finalKey:"DFD 4요소 = Process·Flow·Store·Terminator",sourceImageUrl:"https://drive.google.com/file/d/1_yB0zngV5ZX93SzSLr4gdDCbvHmZwGwA/view"},
  {id:"sujebi-2026-sw-design-ch01-08",sourceQuestionNo:8,sourcePage:"1-18",questionType:"single_choice",questionText:"자료 흐름도(DFD)의 요소별 표기 형태의 연결이 옳지 않은 것은?",choices:["Process: 원","Data Flow: 화살표","Data Store: 삼각형","Terminator: 사각형"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"Data Store는 평행선으로 표현한다. 삼각형은 DFD의 데이터 저장소 표기가 아니다.",finalKey:"DFD Data Store = 평행선",sourceImageUrl:"https://drive.google.com/file/d/11HamwdGJrbypYD8T1qFjESOzcZI5e1wp/view"},
  {id:"sujebi-2026-sw-design-ch01-09",sourceQuestionNo:9,sourcePage:"1-18",questionType:"single_choice",questionText:"UML 확장 모델에서 스테레오 타입 객체를 표현할 때 사용하는 기호로 맞는 것은?",choices:["<< >>","(( ))","{{ }}","[[ ]]"],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"UML의 스테레오타입은 길러멧(Guillemet) 기호 << >> 안에 이름을 넣어 표현한다.",finalKey:"UML Stereotype = << >>",sourceImageUrl:"https://drive.google.com/file/d/11HamwdGJrbypYD8T1qFjESOzcZI5e1wp/view"},
  {id:"sujebi-2026-sw-design-ch01-10",sourceQuestionNo:10,sourcePage:"1-18",questionType:"single_choice",questionText:"UML 모델에서 사용하는 Structural Diagram에 속하지 않는 것은?",choices:["Class Diagram","Object Diagram","Component Diagram","Activity Diagram"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"Class, Object, Component Diagram은 구조적 다이어그램이다. Activity Diagram은 행위적 다이어그램이다.",finalKey:"Activity = Behavioral, Structural 아님",sourceImageUrl:"https://drive.google.com/file/d/11HamwdGJrbypYD8T1qFjESOzcZI5e1wp/view"},
  {id:"sujebi-2026-sw-design-ch01-11",sourceQuestionNo:11,sourcePage:"1-19",questionType:"single_choice",questionText:"아래 UML 모델에서 '차' 클래스를 상위에 두고 버스, 트럭, 택시 클래스가 하위로 연결된 관계로 옳은 것은?",choices:["추상화 관계","의존 관계","일반화 관계","그룹 관계"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"일반화(Generalization)는 일반적인 개념을 부모 클래스로, 구체적인 개념을 자식 클래스로 표현하는 상속 관계다.",finalKey:"상위 일반 개념 ← 하위 구체 클래스 = Generalization",sourceImageUrl:"https://drive.google.com/file/d/15CT_rBc3OdyW8k_YkVjjIWnzgDCA91fB/view"},
  {id:"sujebi-2026-sw-design-ch01-12",sourceQuestionNo:12,sourcePage:"1-19",questionType:"single_choice",questionText:"UML에서 활용되는 다이어그램 중 시스템의 동작을 표현하는 행위(Behavioral) 다이어그램에 해당하지 않는 것은?",choices:["유스케이스 다이어그램(Use Case Diagram)","시퀀스 다이어그램(Sequence Diagram)","활동 다이어그램(Activity Diagram)","배치 다이어그램(Deployment Diagram)"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"Deployment Diagram은 시스템의 물리적 배치 구조를 표현하는 구조적 다이어그램이다. Use Case, Sequence, Activity는 행위적 다이어그램이다.",finalKey:"Deployment = Structural Diagram",sourceImageUrl:"https://drive.google.com/file/d/15CT_rBc3OdyW8k_YkVjjIWnzgDCA91fB/view"},
  {id:"sujebi-2026-sw-design-ch01-13",sourceQuestionNo:13,sourcePage:"1-20",questionType:"single_choice",questionText:"UML에서 시퀀스 다이어그램의 구성항목에 해당하지 않는 것은?",choices:["생명선","실행","확장","메시지"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"Sequence Diagram의 주요 구성요소에는 객체, 생명선, 실행, 메시지 등이 있다. 확장은 유스케이스 관계와 관련된 개념이다.",finalKey:"Sequence 구성 ≠ 확장",sourceImageUrl:"https://drive.google.com/file/d/1RMOaO7lxiVpPid1fVbdzf1NACJy9Hpdq/view"},
  {id:"sujebi-2026-sw-design-ch01-14",sourceQuestionNo:14,sourcePage:"1-20",questionType:"single_choice",questionText:"기본 유스케이스 수행 시 특별한 조건을 만족할 때 수행하는 유스케이스는?",choices:["연관","확장","선택","특화"],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"확장(extend) 관계는 기본 유스케이스가 특정 조건을 만족할 때 추가 유스케이스가 선택적으로 수행되는 관계다.",finalKey:"특별 조건에서 추가 수행 = Extend",sourceImageUrl:"https://drive.google.com/file/d/1RMOaO7lxiVpPid1fVbdzf1NACJy9Hpdq/view"},
  {id:"sujebi-2026-sw-design-ch01-15",sourceQuestionNo:15,sourcePage:"1-20",questionType:"single_choice",questionText:"UML 다이어그램 중 시스템 내 클래스의 정적 구조를 표현하고 클래스와 클래스, 클래스의 속성 사이의 관계를 나타내는 것은?",choices:["Activity Diagram","Model Diagram","State Diagram","Class Diagram"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"Class Diagram은 클래스와 속성·연산 및 클래스 간 관계를 나타내어 시스템의 정적 구조를 표현한다.",finalKey:"클래스의 정적 구조·관계 = Class Diagram",sourceImageUrl:"https://drive.google.com/file/d/1RMOaO7lxiVpPid1fVbdzf1NACJy9Hpdq/view"},
  {id:"sujebi-2026-sw-design-ch01-16",sourceQuestionNo:16,sourcePage:"1-20",questionType:"single_choice",questionText:"유스케이스(Usecase)에 대한 설명 중 옳은 것은?",choices:["유스케이스 다이어그램은 개발자의 요구를 추출하고 분석하기 위해 주로 사용한다.","액터는 대상 시스템과 상호 작용하는 사람이나 다른 시스템에 의한 역할이다.","사용자 액터는 본 시스템과 데이터를 주고받는 연동 시스템을 의미한다.","연동의 개념은 일반적으로 데이터를 파일이나 정해진 형식으로 넘겨주는 것만을 의미한다."],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"Actor는 대상 시스템과 상호작용하는 외부의 사람 또는 다른 시스템의 역할이다. 유스케이스는 사용자 요구를 중심으로 표현한다.",finalKey:"Actor = 외부 사람 또는 연동 시스템의 역할",sourceImageUrl:"https://drive.google.com/file/d/1RMOaO7lxiVpPid1fVbdzf1NACJy9Hpdq/view"}
];

const currentIdBeforeCh01_01_16 = state.currentRoundIds?.[state.currentIndex];
const knownCh01_01_16 = new Set(QUESTIONS.map(q => q.id));
const addCh01_01_16 = CH01_QUESTIONS_01_16.filter(q => !knownCh01_01_16.has(q.id));
if (addCh01_01_16.length) QUESTIONS.push(...addCh01_01_16);
const orderedCh01_01 = QUESTIONS.filter(q => q.id.startsWith("sujebi-2026-sw-design-ch01-")).sort((a,b) => a.sourceQuestionNo - b.sourceQuestionNo);
const orderedNonCh01_01 = QUESTIONS.filter(q => !q.id.startsWith("sujebi-2026-sw-design-ch01-"));
QUESTIONS.splice(0, QUESTIONS.length, ...orderedCh01_01, ...orderedNonCh01_01);
if (state.mode !== "weak") {
  state.currentRoundIds = QUESTIONS.map(q => q.id);
  const preserved = state.currentRoundIds.indexOf(currentIdBeforeCh01_01_16);
  state.currentIndex = preserved >= 0 ? preserved : Math.min(state.currentIndex || 0, state.currentRoundIds.length - 1);
  saveState();
}
if (typeof renderDashboardV01 === "function") renderDashboardV01();