const CH03_QUESTIONS_69_90 = [
  {id:"sujebi-2026-sw-design-ch03-69",sourceQuestionNo:69,sourcePage:"1-58",questionType:"single_choice",questionText:"객체 지향 설계 원칙 중, 서브 타입(상속받은 하위 클래스)은 어디에서나 자신의 기반 타입(상위 클래스)으로 교체할 수 있어야 함을 의미하는 원칙은?",choices:["ISP(Interface Segregation Principle)","DIP(Dependency Inversion Principle)","LSP(Liskov Substitution Principle)","SRP(Single Responsibility Principle)"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"리스코프 치환 원칙(LSP)은 하위 타입이 상위 타입을 대체해도 프로그램의 올바른 동작이 유지되어야 한다는 원칙이다.",finalKey:"하위 타입이 상위 타입을 대체 가능 = LSP",sourceImageUrl:"https://drive.google.com/file/d/177a5_nevDFt7zkd3DamhTqbNQn1bXSGK/view"},
  {id:"sujebi-2026-sw-design-ch03-70",sourceQuestionNo:70,sourcePage:"1-58",questionType:"single_choice",questionText:"클래스 설계 원칙에 대한 바른 설명은?",choices:["단일 책임 원칙: 하나의 클래스만 변경 가능하다.","개방-폐쇄의 원칙: 클래스는 확장에 대해 열려있어야 하며 변경에 대해 닫혀있어야 한다.","리스코프 교체의 원칙: 여러 개의 책임을 가진 클래스는 하나의 책임을 가진 클래스로 대체되어야 한다.","의존관계 역전의 원칙: 클라이언트는 자신이 사용하는 메서드와 의존관계를 갖지 않도록 해야 한다."],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"개방-폐쇄 원칙(OCP)은 소프트웨어 구성요소가 확장에는 열려 있고 기존 코드의 변경에는 닫혀 있어야 한다는 원칙이다.",finalKey:"확장에는 Open, 변경에는 Closed = OCP",sourceImageUrl:"https://drive.google.com/file/d/177a5_nevDFt7zkd3DamhTqbNQn1bXSGK/view"},
  {id:"sujebi-2026-sw-design-ch03-71",sourceQuestionNo:71,sourcePage:"1-59",questionType:"single_choice",questionText:"객체 지향 소프트웨어 공학에서 하나 이상의 유사한 객체들을 묶어서 하나의 공통된 특성을 표현한 것은?",choices:["트랜잭션","클래스","시퀀스","서브루틴"],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"클래스는 유사한 객체들을 묶어 공통된 속성과 행위를 표현하는 추상화 단위다.",finalKey:"유사 객체의 공통 특성 묶음 = 클래스",sourceImageUrl:"https://drive.google.com/file/d/1e46pjnU7GsRuW7Q7XY4ex_yejrNwmaWe/view"},
  {id:"sujebi-2026-sw-design-ch03-72",sourceQuestionNo:72,sourcePage:"1-59",questionType:"single_choice",questionText:"객체 지향 프로그램 개발 기법에 대한 설명으로 옳지 않은 것은?",choices:["소프트웨어의 재사용률이 높아진다.","절차 중심의 프로그래밍 기법이다.","객체모델의 주요요소는 추상화, 캡슐화, 모듈화가 있다.","설계 시 자료와 자료에 가해지는 프로세서를 묶어 정의하고 관계를 규명한다."],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"객체 지향 개발은 객체 중심의 개발 방법으로 절차 중심 프로그래밍 기법이 아니다.",finalKey:"객체지향 ≠ 절차 중심",sourceImageUrl:"https://drive.google.com/file/d/1e46pjnU7GsRuW7Q7XY4ex_yejrNwmaWe/view"},
  {id:"sujebi-2026-sw-design-ch03-73",sourceQuestionNo:73,sourcePage:"1-59",questionType:"single_choice",questionText:"럼바우(Rumbaugh)의 객체 지향 분석 절차를 가장 바르게 나열한 것은?",choices:["객체 모형 → 동적 모형 → 기능 모형","객체 모형 → 기능 모형 → 동적 모형","기능 모형 → 동적 모형 → 객체 모형","기능 모형 → 객체 모형 → 동적 모형"],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"럼바우 분석은 객체 모델링 → 동적 모델링 → 기능 모델링 순으로 진행한다.",finalKey:"럼바우 = 객체 → 동적 → 기능",sourceImageUrl:"https://drive.google.com/file/d/1e46pjnU7GsRuW7Q7XY4ex_yejrNwmaWe/view"},
  {id:"sujebi-2026-sw-design-ch03-74",sourceQuestionNo:74,sourcePage:"1-59",questionType:"single_choice",questionText:"럼바우의 객체 지향 분석과 거리가 먼 것은?",choices:["기능 모델링","동적 모델링","객체 모델링","정적 모델링"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"럼바우의 세 모델은 객체 모델링, 동적 모델링, 기능 모델링이다. 정적 모델링은 별도 단계가 아니다.",finalKey:"럼바우 3모델 = 객체·동적·기능",sourceImageUrl:"https://drive.google.com/file/d/1e46pjnU7GsRuW7Q7XY4ex_yejrNwmaWe/view"},
  {id:"sujebi-2026-sw-design-ch03-75",sourceQuestionNo:75,sourcePage:"1-60",questionType:"single_choice",questionText:"객체 지향 분석 기법의 하나로 객체 모형, 동적 모형, 기능 모형의 3개 모형을 생성하는 방법은?",choices:["Wirfs-Block Method","Rumbaugh Method","Booch Method","Jacobson Method"],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"럼바우 방법은 객체 모형, 동적 모형, 기능 모형의 세 가지 모델을 사용한다.",finalKey:"객체·동적·기능 3모형 = Rumbaugh",sourceImageUrl:"https://drive.google.com/file/d/1cfCHOJXQ1qj0y-xu-0ZloRaVisIWVX3M/view"},
  {id:"sujebi-2026-sw-design-ch03-76",sourceQuestionNo:76,sourcePage:"1-60",questionType:"single_choice",questionText:"럼바우(Rumbaugh)의 객체 지향 분석 기법 중 자료 흐름도(DFD)를 주로 이용하는 것은?",choices:["기능 모델링","동적 모델링","객체 모델링","정적 모델링"],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"기능 모델링은 프로세스의 자료 흐름을 중심으로 처리 과정을 표현하며 DFD를 사용한다.",finalKey:"DFD = 기능 모델링",sourceImageUrl:"https://drive.google.com/file/d/1cfCHOJXQ1qj0y-xu-0ZloRaVisIWVX3M/view"},
  {id:"sujebi-2026-sw-design-ch03-77",sourceQuestionNo:77,sourcePage:"1-60",questionType:"single_choice",questionText:"럼바우(Rumbaugh) 분석기법에서 정보 모델링이라고도 하며, 시스템에서 요구되는 객체를 찾아내어 속성과 연산을 식별하고 객체들 간의 관계를 규정하여 다이어그램으로 표시하는 모델링은?",choices:["Object","Dynamic","Function","Static"],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"객체 모델링(Object Modeling)은 객체와 속성·연산 및 객체 간 관계를 규정하며 객체 다이어그램으로 표현한다.",finalKey:"정보 모델링 = Object Modeling",sourceImageUrl:"https://drive.google.com/file/d/1cfCHOJXQ1qj0y-xu-0ZloRaVisIWVX3M/view"},
  {id:"sujebi-2026-sw-design-ch03-78",sourceQuestionNo:78,sourcePage:"1-60",questionType:"single_choice",questionText:"럼바우(Rumbaugh)의 객체 지향 분석에서 사용되는 분석 활동 순서로 옳은 것은?",choices:["객체 모델링 → 동적 모델링 → 정적 모델링","객체 모델링 → 동적 모델링 → 기능 모델링","동적 모델링 → 기능 모델링 → 정적 모델링","정적 모델링 → 객체 모델링 → 기능 모델링"],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"럼바우 객체 지향 분석 절차는 객체 모델링 → 동적 모델링 → 기능 모델링 순이다.",finalKey:"객체 → 동적 → 기능",sourceImageUrl:"https://drive.google.com/file/d/1cfCHOJXQ1qj0y-xu-0ZloRaVisIWVX3M/view"},
  {id:"sujebi-2026-sw-design-ch03-79",sourceQuestionNo:79,sourcePage:"1-61",questionType:"single_choice",questionText:"소프트웨어를 개발하기 위한 비즈니스(업무)를 객체와 속성, 클래스와 멤버, 전체와 부분 등으로 나누어서 분석해 내는 기법은?",choices:["객체 지향 분석","구조적 분석","기능적 분석","실시간 분석"],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"업무를 객체·속성·클래스·전체/부분 관계 등 객체 지향 개념으로 나누어 분석하는 것은 객체 지향 분석이다.",finalKey:"업무를 객체·클래스로 분석 = 객체 지향 분석",sourceImageUrl:"https://drive.google.com/file/d/1lRZrSTMBhLk5QQNg1CgEovLwx5LPot0d/view"},
  {id:"sujebi-2026-sw-design-ch03-80",sourceQuestionNo:80,sourcePage:"1-61",questionType:"single_choice",questionText:"객체 지향 분석 기법과 관련한 설명으로 틀린 것은?",choices:["동적 모델링 기법이 사용될 수 있다.","기능 중심으로 시스템을 파악하며 순차적인 처리가 중요시되는 하향식(Top-down) 방식으로 볼 수 있다.","데이터와 행위를 하나로 묶어 객체를 정의하고 추상화시키는 작업이라 할 수 있다.","코드 재사용에 의한 프로그램 생산성 향상 및 요구에 따른 시스템의 쉬운 변경이 가능하다."],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"객체 지향 분석은 객체 중심이며 일반적으로 상향식(Bottom-up) 접근으로 본다. 기능 중심 하향식 설명은 구조적 분석에 가깝다.",finalKey:"객체 지향 분석 = 객체 중심·상향식",sourceImageUrl:"https://drive.google.com/file/d/1lRZrSTMBhLk5QQNg1CgEovLwx5LPot0d/view"},
  {id:"sujebi-2026-sw-design-ch03-81",sourceQuestionNo:81,sourcePage:"1-61",questionType:"single_choice",questionText:"객체 지향 기법에서 클래스들 사이의 '부분-전체(part-whole)' 관계 또는 '부분(is-a-part-of)'의 관계로 설명되는 연관성을 나타내는 용어는?",choices:["일반화","추상화","캡슐화","집단화"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"집단화(Aggregation)는 is-part-of 또는 part-whole 관계로 전체와 부분의 관계를 나타낸다.",finalKey:"part-whole / is-part-of = 집단화",sourceImageUrl:"https://drive.google.com/file/d/1lRZrSTMBhLk5QQNg1CgEovLwx5LPot0d/view"},
  {id:"sujebi-2026-sw-design-ch03-82",sourceQuestionNo:82,sourcePage:"1-61",questionType:"single_choice",questionText:"객체 지향 분석 방법론 중 E-R 다이어그램을 사용하여 객체 행위를 모델링하며, 객체 식별, 구조 식별, 주체 정의, 속성 및 관계 정의, 서비스 정의 등의 과정으로 구성되는 것은?",choices:["Coad와 Yourdon 방법","Booch 방법","Jacobson 방법","Wirfs-Brocks 방법"],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"Coad와 Yourdon 방법은 E-R 다이어그램을 사용하고 객체 식별, 구조 식별, 주체 정의, 속성·관계 및 서비스 정의 과정을 수행한다.",finalKey:"E-R + 객체/구조/주체/속성·관계/서비스 = Coad & Yourdon",sourceImageUrl:"https://drive.google.com/file/d/1lRZrSTMBhLk5QQNg1CgEovLwx5LPot0d/view"},
  {id:"sujebi-2026-sw-design-ch03-83",sourceQuestionNo:83,sourcePage:"1-62",questionType:"single_choice",questionText:"객체 지향 소프트웨어 설계 시 디자인 패턴을 구성하는 요소로서 가장 거리가 먼 것은?",choices:["개발자 이름","문제 및 배경","사례","샘플 코드"],sourceAnswer:1,aiDetectedAnswer:1,aiReasonedAnswer:1,sourceExplanation:"디자인 패턴은 일반적으로 패턴 이름, 문제와 배경, 솔루션, 사례, 결과, 샘플 코드 등으로 구성되며 개발자 이름은 핵심 구성요소가 아니다.",finalKey:"디자인 패턴 구성요소 ≠ 개발자 이름",sourceImageUrl:"https://drive.google.com/file/d/1mrIgqlTH9xhte9-y4yC0yGd_y_JGX3bN/view"},
  {id:"sujebi-2026-sw-design-ch03-84",sourceQuestionNo:84,sourcePage:"1-62",questionType:"single_choice",questionText:"GoF(Gang of Four)의 디자인 패턴에서 행위 패턴에 속하는 것은?",choices:["Builder","Visitor","Prototype","Bridge"],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"Visitor는 객체 구조의 각 요소에 수행할 연산을 분리하는 행위 패턴이다. Builder와 Prototype은 생성, Bridge는 구조 패턴이다.",finalKey:"Visitor = 행위 패턴",sourceImageUrl:"https://drive.google.com/file/d/1mrIgqlTH9xhte9-y4yC0yGd_y_JGX3bN/view"},
  {id:"sujebi-2026-sw-design-ch03-85",sourceQuestionNo:85,sourcePage:"1-62",questionType:"single_choice",questionText:"디자인 패턴 중에서 행위적 패턴에 속하지 않는 것은?",choices:["커맨드(Command) 패턴","옵저버(Observer) 패턴","프로토타입(Prototype) 패턴","상태(State) 패턴"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"Prototype은 객체 생성 방식을 다루는 생성 패턴이다. Command, Observer, State는 행위 패턴이다.",finalKey:"Prototype = 생성 패턴",sourceImageUrl:"https://drive.google.com/file/d/1mrIgqlTH9xhte9-y4yC0yGd_y_JGX3bN/view"},
  {id:"sujebi-2026-sw-design-ch03-86",sourceQuestionNo:86,sourcePage:"1-62",questionType:"single_choice",questionText:"객체를 생성하기 위한 인터페이스를 정의하여 어떤 클래스가 인스턴스화될 것인지는 서브 클래스가 결정하도록 하며 Virtual-Constructor 패턴이라고도 하는 디자인 패턴은?",choices:["Visitor 패턴","Observer 패턴","Factory Method 패턴","Bridge 패턴"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"Factory Method는 객체 생성 인터페이스는 상위 클래스에서 정의하고 실제 생성 클래스의 결정은 하위 클래스에 맡긴다.",finalKey:"Virtual Constructor = Factory Method",sourceImageUrl:"https://drive.google.com/file/d/1mrIgqlTH9xhte9-y4yC0yGd_y_JGX3bN/view"},
  {id:"sujebi-2026-sw-design-ch03-87",sourceQuestionNo:87,sourcePage:"1-63",questionType:"single_choice",questionText:"디자인 패턴 사용의 장·단점에 대한 설명으로 거리가 먼 것은?",choices:["소프트웨어 구조 파악이 용이하다.","객체 지향 설계 및 구현의 생산성을 높이는 데 적합하다.","재사용을 위한 개발 시간이 단축된다.","절차형 언어와 함께 이용될 때 효율이 극대화된다."],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"디자인 패턴은 객체 지향 설계에서 특히 유용하며 절차형 언어와 함께 사용할 때 효율이 극대화된다고 보기는 어렵다.",finalKey:"디자인 패턴 = 객체 지향 설계에 특히 유용",sourceImageUrl:"https://drive.google.com/file/d/1iMwwrbdFK-xMe76z8OavCqDzzcUtjkd9/view"},
  {id:"sujebi-2026-sw-design-ch03-88",sourceQuestionNo:88,sourcePage:"1-63",questionType:"single_choice",questionText:"GoF(Gang of Four) 디자인 패턴 분류에 해당하지 않는 것은?",choices:["생성 패턴","구조 패턴","행위 패턴","추상 패턴"],sourceAnswer:4,aiDetectedAnswer:4,aiReasonedAnswer:4,sourceExplanation:"GoF 디자인 패턴은 생성(Creational), 구조(Structural), 행위(Behavioral)의 세 범주로 분류한다.",finalKey:"GoF = 생성·구조·행위",sourceImageUrl:"https://drive.google.com/file/d/1iMwwrbdFK-xMe76z8OavCqDzzcUtjkd9/view"},
  {id:"sujebi-2026-sw-design-ch03-89",sourceQuestionNo:89,sourcePage:"1-63",questionType:"single_choice",questionText:"GoF(Gang of Four) 디자인 패턴의 생성 패턴에 속하지 않는 것은?",choices:["추상 팩토리(Abstract Factory)","빌더(Builder)","어댑터(Adapter)","싱글턴(Singleton)"],sourceAnswer:3,aiDetectedAnswer:3,aiReasonedAnswer:3,sourceExplanation:"Adapter는 서로 다른 인터페이스를 맞춰주는 구조 패턴이다. Abstract Factory, Builder, Singleton은 생성 패턴이다.",finalKey:"Adapter = 구조 패턴",sourceImageUrl:"https://drive.google.com/file/d/1iMwwrbdFK-xMe76z8OavCqDzzcUtjkd9/view"},
  {id:"sujebi-2026-sw-design-ch03-90",sourceQuestionNo:90,sourcePage:"1-63",questionType:"single_choice",questionText:"디자인 패턴을 이용한 소프트웨어 재사용으로 얻어지는 장점이 아닌 것은?",choices:["소프트웨어 코드의 품질을 향상시킬 수 있다.","개발 프로세스를 무시할 수 있다.","개발자들 사이의 의사소통을 원활하게 할 수 있다.","소프트웨어의 품질과 생산성을 향상시킬 수 있다."],sourceAnswer:2,aiDetectedAnswer:2,aiReasonedAnswer:2,sourceExplanation:"디자인 패턴은 재사용성과 의사소통, 품질 및 생산성 향상에 도움이 되지만 개발 프로세스를 무시하게 하는 수단은 아니다.",finalKey:"디자인 패턴 사용 ≠ 개발 프로세스 무시",sourceImageUrl:"https://drive.google.com/file/d/1iMwwrbdFK-xMe76z8OavCqDzzcUtjkd9/view"}
];

const currentIdBeforeCh03_69_90 = state.currentRoundIds?.[state.currentIndex];
const ch03Known69_90 = new Set(QUESTIONS.map(q => q.id));
const ch03Add69_90 = CH03_QUESTIONS_69_90.filter(q => !ch03Known69_90.has(q.id));
if (ch03Add69_90.length) QUESTIONS.push(...ch03Add69_90);

const orderedCh03 = QUESTIONS.filter(q => q.id.startsWith("sujebi-2026-sw-design-ch03-")).sort((a,b) => a.sourceQuestionNo - b.sourceQuestionNo);
const orderedNonCh03 = QUESTIONS.filter(q => !q.id.startsWith("sujebi-2026-sw-design-ch03-"));
QUESTIONS.splice(0, QUESTIONS.length, ...orderedCh03, ...orderedNonCh03);

if (state.mode !== "weak") {
  state.currentRoundIds = QUESTIONS.map(q => q.id);
  const preserved = state.currentRoundIds.indexOf(currentIdBeforeCh03_69_90);
  state.currentIndex = preserved >= 0 ? preserved : Math.min(state.currentIndex || 0, state.currentRoundIds.length - 1);
  saveState();
}
if (typeof renderDashboardV01 === "function") renderDashboardV01();
